### ISSUE TITLE
Prompt user on launch when a new version is out

### ISSUE THREAD

**Issue by JamesMonkey** [BramStoutProductions/MiEx#10]
A little QoL feature would be for when a new version is out for MiEx, without having to check GitHub

Prompt on the launch of MiEx:

Patch notes v1.2.1
-  New feature: Added an Auto-Updater
-  Bug fix: Crash when ___
etc.

At the bottom of the prompt would be two options:

- "Download and install" would handle grabbing the latest version and installing MiEx in the same working directory folder.
- "Skip this version" would not prompt the user again until a higher version number is released.

**Comment by OfficialCRUGG** [comment]
That would be a great addition! Could easily be done by using the GitHub API to fetch the latest release and check if the version is higher. Changelog could also be obtained through there.

Potentially prompt the user on first launch if they want to enable this or not.

**Comment by BramStout** [comment]
I have just released a new version which features a very simple version of this. It checks for a new version and if so, it will show a non-intrusive banner at the top that lets you know that there is a new version out, with a link to download it. There's also an 'x' to close that banner.

Maybe in the future I'll add in that it can also download an install it for you, but for now I hope this will suffice.

Here's the link to the latest version: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.0
