### ISSUE TITLE
[Crashes On Addon] New Addon Chaos

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#102]
The new addon is literally crashing in blender on the most little world you can see, that is not nice and i cannot even do my projects without Old Addon anymore, will this be fixed?...

**Comment by Fyoncle** [comment]
@michal212345

**Comment by michal212345** [comment]
Hey, that sucks the importer does not work for you. What version of blender are you using? And could you send me the crash message from the System Console

**Comment by Fyoncle** [comment]
> Hey, that sucks the importer does not work for you. What version of blender are you using? And could you send me the crash message from the System Console

Not sure how to access the System Console of Blender after a crash, i use 4.1.1 but also crashes on other versions.

**Comment by michal212345** [comment]
> > Hey, that sucks the importer does not work for you. What version of blender are you using? And could you send me the crash message from the System Console
> 
> Not sure how to access the System Console of Blender after a crash, i use 4.1.1 but also crashes on other versions.

For the System console, its window > Show System Console.
Also, do you crash straight to the desktop, or does it freeze for a moment? If you crash to desktop, your crash logs are stored in your `%TEMP%` folder [https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#crash-log](url)

I have a large USD file created by MiEx with very complex materials and models that took about two minutes to load and could be longer, depending on your hardware.

**Comment by Fyoncle** [comment]
> > > Hey, that sucks the importer does not work for you. What version of blender are you using? And could you send me the crash message from the System Console
> > 
> > 
> > Not sure how to access the System Console of Blender after a crash, i use 4.1.1 but also crashes on other versions.
> 
> For the System console, its window > Show System Console. Also, do you crash straight to the desktop, or does it freeze for a moment? If you crash to desktop, your crash logs are stored in your `%TEMP%` folder [https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#crash-log](url)
> 
> I have a large USD file created by MiEx with very complex materials and models that took about two minutes to load and could be longer, depending on your hardware.

It first waits normally, then doesn't respond and instantly shuts down.

**Comment by Fyoncle** [comment]
[crasheddd.crash.txt](https://github.com/user-attachments/files/16513717/crasheddd.crash.txt)
Heres the log, i can't see nothing in it.

**Comment by michal212345** [comment]
> [crasheddd.crash.txt](https://github.com/user-attachments/files/16513717/crasheddd.crash.txt) Heres the log, i can't see nothing in it.

Your blender is trying to read data that do not exist, as the error is as vague as possible I can not reproduce the problem with Blender 4.2 and a fresh install of 4.1.1. I can't help with any more solid reason as to why it's crashing. I can suggest, Disabling any unnecessary Blender plugins, if you installed Blender from Steam, right-click Blender in Steam, Properties > Installed Files > Verify integrity of software files, to check if you have any corrupted files.

**Comment by Fyoncle** [comment]
> Contributor

Try a HUGE world with LODs

**Comment by michal212345** [comment]
> > Contributor
> 
> Try a HUGE world with LODs

How big are we talking? Can you send me a screenshot from miex, you could be possibly just running out of ram

**Comment by Fyoncle** [comment]
> > > Contributor
> > 
> > 
> > Try a HUGE world with LODs
> 
> How big are we talking? Can you send me a screenshot from miex, you could be possibly just running out of ram

![image](https://github.com/user-attachments/assets/bf349529-e5ef-47ae-b9f3-c5dc7c5e0a52)

**Comment by Fyoncle** [comment]
I even tried bigger than that, it mysteriously didnt crash in the previous try, but now it did.

**Comment by michal212345** [comment]
> I even tried bigger than that, it mysteriously didnt crash in the previous try, but now it did.
> 
> In the even bigger one, i tried to import like 7 times after a crash and in the last one it finally worked.

So you managed to get it to import? What is your ram usage like?

**Comment by Fyoncle** [comment]
> > I even tried bigger than that, it mysteriously didnt crash in the previous try, but now it did.
> > In the even bigger one, i tried to import like 7 times after a crash and in the last one it finally worked.
> 
> So you managed to get it to import? What is your ram usage like?

I don't know, it was a few days ago.

**Comment by Fyoncle** [comment]
Any news on this?

**Comment by michal212345** [comment]
I cannot fix this as it seems to be a blender bug with USD; if the old import scripts work fine, please continue using it.
