### ISSUE TITLE
Error while importing world with custom rescource pack (utf-8 codec cant decode byte 0xa7 in position 94: invalid start byte)

### ISSUE THREAD

**Issue by tuen12345** [BramStoutProductions/MiEx#103]
When i import my world with the attached rescource pack config in blender 4.0 with the latest release of the blender addon i get the attached error. I only get this error when using this texture pack --> https://kdpack.nl/
without any texture packs (only base rescource pack+blender) it imports just fine

<img width="232" alt="Screenshot 2024-08-20 171934" src="https://github.com/user-attachments/assets/bce3a32e-0614-4819-a839-3c8e4b3f3626">
<img width="554" alt="Screenshot 2024-08-20 171649" src="https://github.com/user-attachments/assets/1267b3dd-e3ac-4122-9ea7-8e8b878a8e4c">

**Comment by BramStout** [comment]
It looks like the `§` character in the resource pack's name is causing the issue. Could you try renaming the resource pack folder to remove the § characters and then try exporting out a world again?
