### ISSUE TITLE
Dokucraft Biome Color Glitch

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#108]
![image](https://github.com/user-attachments/assets/53dedb26-a135-4da6-8369-d3f3a2a92aa8)
Biome colors in Dokucraft is being white because it's "tinted"

We just realized there is a json called "miex_block_tints" but i have no damn idea how this works, is this something fixable on our end? or is it a glitch.

**Comment by Lodemor** [comment]
Hi! Original poser of the problem (Fyoncle sent it on my behalf)

The issue was modded biome colors, without the mod resource pack in place, it turns all unknown biome colors white.
Adding the mod resources in this order (Blender template) > (Texture Pack) > (Mod resource) > base fixes the issue

**Comment by Fyoncle** [comment]
Oh, our bad then :v
