### ISSUE TITLE
Dependency cycle detected when importing to Blender.

### ISSUE THREAD

**Issue by xboxer214** [BramStoutProductions/MiEx#11]
Anytime I try to import the USD to Blender, I get this error in the console.

![image_2024-04-24_031838671](https://github.com/BramStoutProductions/MiEx/assets/7522933/0c37387e-ddb0-4816-8eab-7de808d07f6d)

**Comment by xboxer214** [comment]
Wait, that was a different error, this is what I get now. 
![image_2024-04-24_041001547](https://github.com/BramStoutProductions/MiEx/assets/7522933/09546bd6-e83d-4356-8955-35d23988ddbe)

**Comment by BramStout** [comment]
Hi! Would you be able to try the latest release? https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.1

I have tested importing into Blender 4.0 and 4.1 when exporting out using this and it's working for me. If it's still not working for you, would you then be able to send me the USD files of the export?

**Comment by xboxer214** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/7522933/df61582a-c0a6-4003-9d43-f6cb983bec32)

Well, now I get this

**Comment by xboxer214** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/7522933/fefefffd-13e5-4a7e-801c-709526311b04)
[log.txt](https://github.com/BramStoutProductions/MiEx/files/15095102/log.txt)

**Comment by xboxer214** [comment]
Similar as before.
![image](https://github.com/BramStoutProductions/MiEx/assets/7522933/766628f2-fff4-40ef-af03-bdf53a6ed090)

**Comment by BramStout** [comment]
Hi! That error was due to a bug related to the base_resource_pack not being properly loaded on first launch. This has now been fixed in the latest release: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.2

Hopefully, it should now all work!

**Comment by xboxer214** [comment]
Log from trying to open a 1.12.2 Modpack, as it failed to open.
[log.txt](https://github.com/BramStoutProductions/MiEx/files/15096088/log.txt)

**Comment by BramStout** [comment]
Currently, MiEx only supports Minecraft 21w43a and up. I haven't had the time to add in support for older chunk formats. 21w43a is part of 1.18.

**Comment by xboxer214** [comment]
Gotcha, gonna test on some newer modpacks then.

**Comment by BramStout** [comment]
For modded blocks, MiEx needs to know how to handle those blocks. It does this by looking for a blockstate file. The blockstate files for vanilla blocks are located in `base_resource_pack/assets/minecraft/blockstates`  So the block `minecraft:stone` would be the blockstate file `assets/minecraft/blockstates/stone.json`  A block like `mod:custom_block` would be `assets/mod/blockstates/custom_block.json`

So, to allow MiEx to be able to export out custom blocks, you need to create the blockstate files for it and also the accompanying block model files. Depending on how the mod was created, they might already have these files somewhere in the mod's jar file, so all you'd need to do is extract them out into a resource pack and then enable that resource pack in MiEx

**Comment by Fyoncle** [comment]
> For modded blocks, MiEx needs to know how to handle those blocks. It does this by looking for a blockstate file. The blockstate files for vanilla blocks are located in `base_resource_pack/assets/minecraft/blockstates` So the block `minecraft:stone` would be the blockstate file `assets/minecraft/blockstates/stone.json` A block like `mod:custom_block` would be `assets/mod/blockstates/custom_block.json`
> 
> So, to allow MiEx to be able to export out custom blocks, you need to create the blockstate files for it and also the accompanying block model files. Depending on how the mod was created, they might already have these files somewhere in the mod's jar file, so all you'd need to do is extract them out into a resource pack and then enable that resource pack in MiEx

How we extract them into a resource pack? can you get in deep down details please?

**Comment by Fyoncle** [comment]
> > > For modded blocks, MiEx needs to know how to handle those blocks. It does this by looking for a blockstate file. The blockstate files for vanilla blocks are located in `base_resource_pack/assets/minecraft/blockstates` So the block `minecraft:stone` would be the blockstate file `assets/minecraft/blockstates/stone.json` A block like `mod:custom_block` would be `assets/mod/blockstates/custom_block.json`
> > > So, to allow MiEx to be able to export out custom blocks, you need to create the blockstate files for it and also the accompanying block model files. Depending on how the mod was created, they might already have these files somewhere in the mod's jar file, so all you'd need to do is extract them out into a resource pack and then enable that resource pack in MiEx
> > 
> > 
> > How we extract them into a resource pack? can you get in deep down details please?
> 
> It depends on the specific mod. Basically, you need to create a resource pack that specifies block states and block models (and textures if needed). This is done just like any normal resource pack. The Minecraft Wiki is the best place to learn about making resource packs: https://minecraft.wiki/w/Resource_pack
> 
> For some mods, you need to create the block state and block model files yourself. But some other mods use block states and block models, just like vanilla Minecraft. In that case, you can probably find the block state and block model files inside of the mod's jar file.
> 
> For example, for the mod [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries), it essentially has a built in resource pack which you can find right here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources So, you'd take the contents of that `resources` folder and put it into a folder called `Supplementaries` (or any other name) and place that folder in the `resources` folder that's next to the MiEx.jar file. Now, you'll have a resource pack called `Supplementaries` show up in MiEx and if you enable it, you'll be able to export out any world that uses blocks from this mod.

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/29dbdb9e-7696-41fd-8064-dcf899c38c66)
I don't meant to do it like that??? because it doesnt work at all.
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/081d61b7-5f36-482e-9cdd-2236ce0b00a3)
Trees still not in place.

**Comment by BramStout** [comment]
No, all of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.

I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.

**Comment by Fyoncle** [comment]
> All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> 
> I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.

can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?

**Comment by Fyoncle** [comment]
> All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> 
> I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/9683f107-e078-4e8d-9391-c75dbcd6a970)
Not works like that also, both folders contain textures and blockstates.

**Comment by BramStout** [comment]
> > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> 
> can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?

Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources

You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.

You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.

In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world

**Comment by Fyoncle** [comment]
> > > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> > 
> > 
> > can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?
> 
> Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources
> 
> You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.
> 
> You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.
> 
> In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/44005ab9-e281-4c4e-ae5f-dc838acd5767)
Now whole world made of flowers, magma blocks, iron ores and more, it even more messed up and modded stuff not even there!!! :(

**Comment by BramStout** [comment]
> > > > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > > > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> > > 
> > > 
> > > can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?
> > 
> > 
> > Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources
> > You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.
> > You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.
> > In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world
> 
> ![image](https://private-user-images.githubusercontent.com/63975256/325359312-44005ab9-e281-4c4e-ae5f-dc838acd5767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg1ODksIm5iZiI6MTcxMzk4ODI4OSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNTkzMTItNDQwMDVhYjktZTI4MS00YzRlLWFlNWYtZGM4MzhhY2Q1NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmVlMjQyZDVhY2E4MzVhZGI4YjBiY2I2ZjNlM2FkMWI0ODlmODcyOGRhMWFlOWNmZGNjMDBjOGIwMGYxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQYJbFVz5SWBlgEYqMzHlvnfO-8fiQU7w690SURvnrY) Now whole world made of flowers, magma blocks, iron ores and more, it even more messed up and modded stuff not even there!!! :(

I'll have a look tomorrow if I can get it working on my end with this specific mod and I'll get back to you then.

**Comment by Fyoncle** [comment]
> > > > > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > > > > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> > > > 
> > > > 
> > > > can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?
> > > 
> > > 
> > > Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources
> > > You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.
> > > You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.
> > > In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/63975256/325359312-44005ab9-e281-4c4e-ae5f-dc838acd5767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg1ODksIm5iZiI6MTcxMzk4ODI4OSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNTkzMTItNDQwMDVhYjktZTI4MS00YzRlLWFlNWYtZGM4MzhhY2Q1NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmVlMjQyZDVhY2E4MzVhZGI4YjBiY2I2ZjNlM2FkMWI0ODlmODcyOGRhMWFlOWNmZGNjMDBjOGIwMGYxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQYJbFVz5SWBlgEYqMzHlvnfO-8fiQU7w690SURvnrY) Now whole world made of flowers, magma blocks, iron ores and more, it even more messed up and modded stuff not even there!!! :(
> 
> I'll have a look tomorrow if I can get it working on my end with this specific mod and I'll get back to you then.

Theres trillions of variants of the texture packs the more you click, heres an video of this huge glitch.

https://github.com/BramStoutProductions/MiEx/assets/63975256/98441359-ca95-417b-9537-dc9ea97620a1

**Comment by Fyoncle** [comment]
> > > > > > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > > > > > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> > > > > 
> > > > > 
> > > > > can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?
> > > > 
> > > > 
> > > > Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources
> > > > You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.
> > > > You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.
> > > > In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/63975256/325359312-44005ab9-e281-4c4e-ae5f-dc838acd5767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg1ODksIm5iZiI6MTcxMzk4ODI4OSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNTkzMTItNDQwMDVhYjktZTI4MS00YzRlLWFlNWYtZGM4MzhhY2Q1NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmVlMjQyZDVhY2E4MzVhZGI4YjBiY2I2ZjNlM2FkMWI0ODlmODcyOGRhMWFlOWNmZGNjMDBjOGIwMGYxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQYJbFVz5SWBlgEYqMzHlvnfO-8fiQU7w690SURvnrY) Now whole world made of flowers, magma blocks, iron ores and more, it even more messed up and modded stuff not even there!!! :(
> > 
> > 
> > I'll have a look tomorrow if I can get it working on my end with this specific mod and I'll get back to you then.
> 
> Theres trillions of variants of the texture packs the more you click, heres an video of this huge glitch.
> 
>  Insane.Glitch.mp4

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/19ac6367-d983-4cb9-bcc5-8e6b34064866)
And results are crazy worlds made of flower, but this way you can get some modded textures if u click a million times enough and find the right texture out of trillion variants lmao.

**Comment by BramStout** [comment]
> > > > > > > All of the files do need to be located in a specific folder structure. All of the block state json files need to be in `assets/<mod namespace>/blockstates`, all of the block model json files need to be in `assets/<mod namespace>/models/block`, and all of the block textures need to be in `assets/<mod namespace>/textures/block`.
> > > > > > > I'd recommend to look at this link here: https://github.com/MehVahdJukaar/Supplementaries/tree/1.20-split/common/src/main/resources This shows you the structure of resource packs that MiEx needs.
> > > > > > 
> > > > > > 
> > > > > > can you tell me an example? the biome mod im using is "Regions Unexplored" how should i type it, what folders i should create inside of the resources folder of MiEx?
> > > > > 
> > > > > 
> > > > > Here you can find the internal resource pack that Regions Unexplored uses: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4/src/main/resources
> > > > > You can go to the main GitHub page for Regions Explored ( https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/tree/1.20.4 ) and click on the green "Code" button to download it as a zip. Then you extract that zip file somewhere (doesn't matter where). In there, you go to `src/main/resources`. You take the contents of that folder and copy it into a new folder located in the `resources` folder that's next to the MiEx.jar file. You could name that new folder something like `Regions Unexplored`.
> > > > > You should then have the following structure `resources/Regions Unexplored/assets/regions_unexplored/blockstates`, `resources/Regions Unexplored/assets/regions_unexplored/models`, and `resources/Regions Unexplored/assets/regions_unexplored/textures`.
> > > > > In theory, when you then load in the world and enable the Regions Unexplored resource pack, it should also show the correct colours for the blocks from that mod in the top-down view of the world
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/63975256/325359312-44005ab9-e281-4c4e-ae5f-dc838acd5767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODg1ODksIm5iZiI6MTcxMzk4ODI4OSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNTkzMTItNDQwMDVhYjktZTI4MS00YzRlLWFlNWYtZGM4MzhhY2Q1NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmVlMjQyZDVhY2E4MzVhZGI4YjBiY2I2ZjNlM2FkMWI0ODlmODcyOGRhMWFlOWNmZGNjMDBjOGIwMGYxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQYJbFVz5SWBlgEYqMzHlvnfO-8fiQU7w690SURvnrY) Now whole world made of flowers, magma blocks, iron ores and more, it even more messed up and modded stuff not even there!!! :(
> > > 
> > > 
> > > I'll have a look tomorrow if I can get it working on my end with this specific mod and I'll get back to you then.
> > 
> > 
> > Theres trillions of variants of the texture packs the more you click, heres an video of this huge glitch.
> > Insane.Glitch.mp4
> 
> ![image](https://private-user-images.githubusercontent.com/63975256/325369437-19ac6367-d983-4cb9-bcc5-8e6b34064866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTU3NzQsIm5iZiI6MTcxNDA1NTQ3NCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjUzNjk0MzctMTlhYzYzNjctZDk4My00Y2I5LWJjYzUtOGU2YjM0MDY0ODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE0MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDAyNTA2NDA1NzU2YjBlZTIxNDRkYjY5YWQ0MzQ2ZGNjMWM4ZjYzZTAyNzJkNGU1MmMwMDMyNTA2YzZlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4ktVTl7Jll8F0O1nygs5Br7N2qVJIqGboUHETaoZig) And results are crazy worlds made of flower, but this way you can get some modded textures if u click a million times enough and find the right texture out of trillion variants lmao.

Hi! I have got it working on my computer now: 
![image](https://github.com/BramStoutProductions/MiEx/assets/128681226/3c33c181-2aa6-467d-8a35-b32dee217734)

It turned out that there was a small bug in the loading of block models that caused it to not generate meshes properly. The latest version of MiEx has it now fixed. You can find it here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.3.0 

Here is also an example resource pack for Regions Unexplored. The zip file contains a folder called `Regions_Unexplored`. Place that folder in the `resources` folder and it should work.
[Regions_Unexplored.zip](https://github.com/BramStoutProductions/MiEx/files/15111672/Regions_Unexplored.zip)
