### ISSUE TITLE
[Bug]: Specific Resource Pack Missing Textures

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#112]
Patrix's some of the leaves are like that.
![image](https://github.com/user-attachments/assets/814c88ad-aa82-43c5-90ea-17d1308f9302)

**Comment by BramStout** [comment]
This is a bug in the Blender import addon. Blender limits the names of materials and shading nodes to 63 characters which the addon doesn't take into account (we weren't aware of this limit when writing the addon). The Blender addon will hopefully soon be updated with a fix

**Comment by BramStout** [comment]
The Blender import addon has been updated with a fix for this bug. You can find the new version of the addon here: https://github.com/BramStoutProductions/MiEx/blob/main/extras/Blender/BlenderAddon/MiExImport.py

**Comment by Fyoncle** [comment]
Thanks!
