### ISSUE TITLE
Missing "self" References in Blender Python Script [FIX]

### ISSUE THREAD

**Issue by Warwlock** [BramStoutProductions/MiEx#115]
When I try to import my world to blender textures weren't importing. So I looked up for the code and there was missing references for `"data['network'].items()" at line 33` and `data['terminals'].items() at line 58` and `mat.use_backface_culling = True at line 69` under the SetupMaterials class. I just added "self" to the beginning of each code.

It is relatively easy fix but sorry for my laziness not looking for how to pull request. (Also I didn't do pull request before so I didn't bothered to try.)

Edit: And also I added `self.data = data` to the `__init__` of the class.

**Comment by BramStout** [comment]
Thank you for letting me know about this and providing your fix for it! I've updated the addon
