### ISSUE TITLE
Blender Addon Broken At 4.3.0

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#118]
It gives some pyhton errors and doesn't add the textures.

**Comment by Aspirata** [comment]
What errors exactly ?

**Comment by Fyoncle** [comment]
> What errors exactly ?

Just import it and see :v

**Comment by Aspirata** [comment]
I can't export the world because I don't have mojang minecraft launcher, so MiEx can't find the base_resource_pack

**Comment by michal212345** [comment]
In Blender 4.3, they deprecated and removed `Material.shadow_method`. Removing the line fixes the plugin.
[Source ](https://developer.blender.org/docs/release_notes/4.3/python_api/#eevee)

**Comment by Fyoncle** [comment]
> In Blender 4.3, they deprecated and removed `Material.shadow_method`. Removing the line fixes the plugin. [Source ](https://developer.blender.org/docs/release_notes/4.3/python_api/#eevee)

So why not open a pr or update the addon! :D

**Comment by michal212345** [comment]
On it rn

**Comment by Fyoncle** [comment]
> On it rn

❤️

**Comment by BramStout** [comment]
The fix has been merged into the repository and the updated addon can be found here: https://github.com/BramStoutProductions/MiEx/tree/main/extras/Blender/BlenderAddon
