### ISSUE TITLE
Forced-Walk Chunks

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#23]
Cannot export ANY chunk that i didn't walk on inside the game, all chunks has to be used by the player before being possible to use, or they will be invisible on blender, is it possible to fix this also?

**Comment by BramStout** [comment]
MiEx currently only supports chunks written by Minecraft 21w43a or later. This is perfectly fine for new worlds created in the past two and a half years, but for any world created before that, you can end up with chunks that MiEx currently cannot load. Minecraft only updates the chunk to the latest version, when it actually loads it in and then saves it.

The goal is definitely to add in support for older versions of Minecraft, but we hadn't needed it so far, so support for it was never added in.

**Comment by Fyoncle** [comment]
> MiEx currently only supports chunks written by Minecraft 21w43a or later. This is perfectly fine for new worlds created in the past two and a half years, but for any world created before that, you can end up with chunks that MiEx currently cannot load. Minecraft only updates the chunk to the latest version, when it actually loads it in and then saves it.
> 
> The goal is definitely to add in support for older versions of Minecraft, but we hadn't needed it so far, so support for it was never added in.

That world created a week ago..

**Comment by BramStout** [comment]
Are you by any chance using the mod Distant Horizons? If so, the chunks generated by that mod can't be read by MiEx. It can only read the chunks generated by Minecraft itself.

If not, would you be able to share the world so that I can look into what's going on?

**Comment by Fyoncle** [comment]
> Are you by any chance using the mod Distant Horizons? If so, the chunks generated by that mod can't be read by MiEx. It can only read the chunks generated by Minecraft itself.
> 
> If not, would you be able to share the world so that I can look into what's going on?

Nooo i don't use this mod.
Also world is a bit too big so, i use elysium days modpack and i can give you the seed if you want.

**Comment by BramStout** [comment]
I'll try exporting a world created using that mod-pack sometime this week, to see if I can reproduce the issue.

In the mean time, would you be able to check if you still get this issue when using vanilla Minecraft? Just to check whether the issue has something to do with the mod-pack or not.

**Comment by Fyoncle** [comment]
> I'll try exporting a world created using that mod-pack sometime this week, to see if I can reproduce the issue.
> 
> In the mean time, would you be able to check if you still get this issue when using vanilla Minecraft? Just to check whether the issue has something to do with the mod-pack or not.

Also on vanilla maps sir.

**Comment by BramStout** [comment]
Do the chunks, that don't show up in Blender, show up in the top-down view of the world in MiEx? After having done an export, MiEx will have created a file called `log.txt` next to the MiEx.jar file. Could you share that log.txt file?

**Comment by Fyoncle** [comment]
> Do the chunks, that don't show up in Blender, show up in the top-down view of the world in MiEx? After having done an export, MiEx will have created a file called `log.txt` next to the MiEx.jar file. Could you share that log.txt file?

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/d314726c-a3bf-43c3-876f-2893fc74ec77)
Okay so, even tho i walk on them it just doesn't load at all now, and there was a insane log spam when i TP into this coordinates, heres the log file; [log.txt](https://github.com/BramStoutProductions/MiEx/files/15105168/log.txt)

**Comment by BramStout** [comment]
Looking at the log, it almost looks like the chunk data itself is corrupt, although assuming that Minecraft loads it properly I doubt that's actually the case. Would you be able to share with me a vanilla world where this issue happens together with the coordinates of where it happens?

**Comment by Fyoncle** [comment]
> Looking at the log, it almost looks like the chunk data itself is corrupt, although assuming that Minecraft loads it properly I doubt that's actually the case. Would you be able to share with me a vanilla world where this issue happens together with the coordinates of where it happens?

-665 -32 146
https://drive.google.com/file/d/1ZFehus7xtN0wxysxfcHmLyCzxVFJuCOM/view?usp=sharing

**Comment by Fyoncle** [comment]
> > > Looking at the log, it almost looks like the chunk data itself is corrupt, although assuming that Minecraft loads it properly I doubt that's actually the case. Would you be able to share with me a vanilla world where this issue happens together with the coordinates of where it happens?
> > 
> > 
> > -665 -32 146 https://drive.google.com/file/d/1ZFehus7xtN0wxysxfcHmLyCzxVFJuCOM/view?usp=sharing
> 
> I've just tried loading in that world using the latest release of MiEx ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.3.0 ) and it loads up perfectly fine for me. I'm not able to reproduce the issue, unfortunately.
> 
> Would you be able to try loading the world into the latest version of MiEx and see if the issue still happens?

No chunks load except the ones i travel still in 1.3.0

**Comment by BramStout** [comment]
Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.

**Comment by Fyoncle** [comment]
> Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.
In the warden one?

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/ab4d10ed-9028-4269-bb48-4d59032f9aa1)
When i come here to load these parts of the map, they also blacked out cuz i never walked on them, thats not nice.

**Comment by BramStout** [comment]
> > Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.
> 
> In the warden one?

Any world where you are experiencing the issue. And then please share the log file here.



> ![image](https://private-user-images.githubusercontent.com/63975256/326287474-ab4d10ed-9028-4269-bb48-4d59032f9aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzE4MDAsIm5iZiI6MTcxNDMzMTUwMCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyODc0NzQtYWI0ZDEwZWQtOTAyOC00MjY5LWJiNDgtNGQ1OTAzMmY5YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MmZmYjAyMTViODU5NzBhNjBhY2JhYzhmNzE0YjA1Mjk5YTJlNzQ2Y2E5ZjNiZjA2MGM3Y2UyMWQzZmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvOra5Ky2Kft_ugO_4F7v5YuOP-LjWYEy01VCcKTh4M) When i come here to load these parts of the map, they also blacked out cuz i never walked on them, thats not nice, i want a automatic load algorithm that automates this process without even walking in it in the game.

If it's a bug in MiEx that causes it to not be able to load chunks even though Minecraft can load those chunks, then I'll try to fix it. The issue right now, though, is that I'm not yet able to reproduce that you're experiencing. Once I'm able to reproduce it, I can try to fix it. Having a log file from the latest version of MiEx would hopefully help with this.

If it's not a bug with MiEx, but rather with Minecraft itself (maybe that the chunks didn't get saved, etc.) then I won't be able to do much about it. MiEx won't be able to automatically load in those chunks, because it would then need to load in the entirety of Minecraft itself, which just isn't feasible.

**Comment by Fyoncle** [comment]
> > > Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.
> > 
> > 
> > In the warden one?
> 
> Any world where you are experiencing the issue. And then please share the log file here.
> 
> > ![image](https://private-user-images.githubusercontent.com/63975256/326287474-ab4d10ed-9028-4269-bb48-4d59032f9aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzE4MDAsIm5iZiI6MTcxNDMzMTUwMCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyODc0NzQtYWI0ZDEwZWQtOTAyOC00MjY5LWJiNDgtNGQ1OTAzMmY5YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MmZmYjAyMTViODU5NzBhNjBhY2JhYzhmNzE0YjA1Mjk5YTJlNzQ2Y2E5ZjNiZjA2MGM3Y2UyMWQzZmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvOra5Ky2Kft_ugO_4F7v5YuOP-LjWYEy01VCcKTh4M) When i come here to load these parts of the map, they also blacked out cuz i never walked on them, thats not nice, i want a automatic load algorithm that automates this process without even walking in it in the game.
> 
> If it's a bug in MiEx that causes it to not be able to load chunks even though Minecraft can load those chunks, then I'll try to fix it. The issue right now, though, is that I'm not yet able to reproduce that you're experiencing. Once I'm able to reproduce it, I can try to fix it. Having a log file from the latest version of MiEx would hopefully help with this.
> 
> If it's not a bug with MiEx, but rather with Minecraft itself (maybe that the chunks didn't get saved, etc.) then I won't be able to do much about it. MiEx won't be able to automatically load in those chunks, because it would then need to load in the entirety of Minecraft itself, which just isn't feasible.

I didn't generate these chunks on minecraft, either i didn't walk on it, problem is exactly that, in mineways even tho you dont walk on it the WHOLE WORLD loads, but in MiEx it only loads the chunks you walk on.

**Comment by BramStout** [comment]
> > > > Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.
> > > 
> > > 
> > > In the warden one?
> > 
> > 
> > Any world where you are experiencing the issue. And then please share the log file here.
> > > ![image](https://private-user-images.githubusercontent.com/63975256/326287474-ab4d10ed-9028-4269-bb48-4d59032f9aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzE4MDAsIm5iZiI6MTcxNDMzMTUwMCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyODc0NzQtYWI0ZDEwZWQtOTAyOC00MjY5LWJiNDgtNGQ1OTAzMmY5YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MmZmYjAyMTViODU5NzBhNjBhY2JhYzhmNzE0YjA1Mjk5YTJlNzQ2Y2E5ZjNiZjA2MGM3Y2UyMWQzZmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvOra5Ky2Kft_ugO_4F7v5YuOP-LjWYEy01VCcKTh4M) When i come here to load these parts of the map, they also blacked out cuz i never walked on them, thats not nice, i want a automatic load algorithm that automates this process without even walking in it in the game.
> > 
> > 
> > If it's a bug in MiEx that causes it to not be able to load chunks even though Minecraft can load those chunks, then I'll try to fix it. The issue right now, though, is that I'm not yet able to reproduce that you're experiencing. Once I'm able to reproduce it, I can try to fix it. Having a log file from the latest version of MiEx would hopefully help with this.
> > If it's not a bug with MiEx, but rather with Minecraft itself (maybe that the chunks didn't get saved, etc.) then I won't be able to do much about it. MiEx won't be able to automatically load in those chunks, because it would then need to load in the entirety of Minecraft itself, which just isn't feasible.
> 
> I didn't generate these chunks on minecraft, either i didn't walk on it, problem is exactly that, in mineways even tho you dont walk on it the WHOLE WORLD loads, but in MiEx it only loads the chunks you walk on.

Mineways only loads in the chunks that are generated by Minecraft and saved to disk. This is also the same for MiEx. The two programs both load worlds in the exact same way. When I load in the Warden world that you send me in both programs, they both show the exact same thing and the both show all of the chunks: 
![image](https://github.com/BramStoutProductions/MiEx/assets/128681226/b1522829-c90f-4504-af97-bc0487f968f3)

But for you, you're getting some chunks that aren't loaded:

> > Do the chunks, that don't show up in Blender, show up in the top-down view of the world in MiEx? After having done an export, MiEx will have created a file called `log.txt` next to the MiEx.jar file. Could you share that log.txt file?
> 
> ![image](https://private-user-images.githubusercontent.com/63975256/325495109-d314726c-a3bf-43c3-876f-2893fc74ec77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzQ0NzMsIm5iZiI6MTcxNDMzNDE3MywicGF0aCI6Ii82Mzk3NTI1Ni8zMjU0OTUxMDktZDMxNDcyNmMtYTNiZi00M2MzLTg3NmYtMjg5M2ZjNzRlYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5NTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTdiODM0ZjkwMTliYWI3YWUwMjYxNjE1MDI5N2YyYjhjMDNjODI5YWU4OGI2OTg0NGMwMDU0MzM0MDk4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6yZpdVhegdADRdxRvjBhy6kvg82v4CgKjDDroSyGV8) Okay so, even tho i walk on them it just doesn't load at all now, and there was a insane log spam when i TP into this coordinates, heres the log file; [log.txt](https://github.com/BramStoutProductions/MiEx/files/15105168/log.txt)

I'm not getting that. This means that there is some bug somewhere with MiEx running on your computer that I'm not getting. Because I'm not getting that issue, I'm not able to reproduce it, and so I'm not able to fix it, because I'm not able to figure out what's actually going on.

This is why I'm asking for you to load in the world in the latest version of MiEx, verify that chunks aren't loading that are being loaded in Mineways, **and then share the log.txt file that MiEx generates with me here**. Hopefully, that log.txt file will have some clue in it on what's going on, so that I might be able to fix it.

**Comment by Fyoncle** [comment]
> > > > > Would you be able to try it in the latest version ( https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0 ) and then share the log file? The log file will now contain a few pieces of information about your Java install, which could help me figure out what's going on.
> > > > 
> > > > 
> > > > In the warden one?
> > > 
> > > 
> > > Any world where you are experiencing the issue. And then please share the log file here.
> > > > ![image](https://private-user-images.githubusercontent.com/63975256/326287474-ab4d10ed-9028-4269-bb48-4d59032f9aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzE4MDAsIm5iZiI6MTcxNDMzMTUwMCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyODc0NzQtYWI0ZDEwZWQtOTAyOC00MjY5LWJiNDgtNGQ1OTAzMmY5YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MmZmYjAyMTViODU5NzBhNjBhY2JhYzhmNzE0YjA1Mjk5YTJlNzQ2Y2E5ZjNiZjA2MGM3Y2UyMWQzZmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvOra5Ky2Kft_ugO_4F7v5YuOP-LjWYEy01VCcKTh4M) When i come here to load these parts of the map, they also blacked out cuz i never walked on them, thats not nice, i want a automatic load algorithm that automates this process without even walking in it in the game.
> > > 
> > > 
> > > If it's a bug in MiEx that causes it to not be able to load chunks even though Minecraft can load those chunks, then I'll try to fix it. The issue right now, though, is that I'm not yet able to reproduce that you're experiencing. Once I'm able to reproduce it, I can try to fix it. Having a log file from the latest version of MiEx would hopefully help with this.
> > > If it's not a bug with MiEx, but rather with Minecraft itself (maybe that the chunks didn't get saved, etc.) then I won't be able to do much about it. MiEx won't be able to automatically load in those chunks, because it would then need to load in the entirety of Minecraft itself, which just isn't feasible.
> > 
> > 
> > I didn't generate these chunks on minecraft, either i didn't walk on it, problem is exactly that, in mineways even tho you dont walk on it the WHOLE WORLD loads, but in MiEx it only loads the chunks you walk on.
> 
> Mineways only loads in the chunks that are generated by Minecraft and saved to disk. This is also the same for MiEx. The two programs both load worlds in the exact same way. When I load in the Warden world that you send me in both programs, they both show the exact same thing and the both show all of the chunks: ![image](https://private-user-images.githubusercontent.com/128681226/326290699-b1522829-c90f-4504-af97-bc0487f968f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzU1NzIsIm5iZiI6MTcxNDMzNTI3MiwicGF0aCI6Ii8xMjg2ODEyMjYvMzI2MjkwNjk5LWIxNTIyODI5LWM5MGYtNDUwNC1hZjk3LWJjMDQ4N2Y5NjhmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMDE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzUxYjRlNjdjOTVmODcyYzAwNTNhODcwOGZjYzEzYTdhYmU0NWYwZGU2OGY0YmJmZmQ0YjUyNTJkY2EzNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RoWBIsBWZypQrGmuUcoDpzuxsRTQOPkXj75AVdsvFGE)
> 
> But for you, you're getting some chunks that aren't loaded:
> 
> > > Do the chunks, that don't show up in Blender, show up in the top-down view of the world in MiEx? After having done an export, MiEx will have created a file called `log.txt` next to the MiEx.jar file. Could you share that log.txt file?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/63975256/325495109-d314726c-a3bf-43c3-876f-2893fc74ec77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzQ0NzMsIm5iZiI6MTcxNDMzNDE3MywicGF0aCI6Ii82Mzk3NTI1Ni8zMjU0OTUxMDktZDMxNDcyNmMtYTNiZi00M2MzLTg3NmYtMjg5M2ZjNzRlYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5NTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTdiODM0ZjkwMTliYWI3YWUwMjYxNjE1MDI5N2YyYjhjMDNjODI5YWU4OGI2OTg0NGMwMDU0MzM0MDk4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6yZpdVhegdADRdxRvjBhy6kvg82v4CgKjDDroSyGV8) Okay so, even tho i walk on them it just doesn't load at all now, and there was a insane log spam when i TP into this coordinates, heres the log file; [log.txt](https://github.com/BramStoutProductions/MiEx/files/15105168/log.txt)
> 
> I'm not getting that. This means that there is some bug somewhere with MiEx running on your computer that I'm not getting. Because I'm not getting that issue, I'm not able to reproduce it, and so I'm not able to fix it, because I'm not able to figure out what's actually going on.
> 
> This is why I'm asking for you to load in the world in the latest version of MiEx, verify that chunks aren't loading that are being loaded in Mineways, **and then share the log.txt file that MiEx generates with me here**. Hopefully, that log.txt file will have some clue in it on what's going on, so that I might be able to fix it.

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/c5f3b131-001f-464b-8cf8-d3301101a8f6)
Somehow fixed in latest build which is 1.4.0, thank you!
