### ISSUE TITLE
Wrong Path & Folder Stuck

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#25]
If a wrong path, or a folder selected accidentaly when opening a world inside of MiEx, you need to restart the program or you cannot gonna select a world again unless you restart.

Also file selector thingy is looks like from 1994 lol, isn't theres a new file explorer to select these map thingys?

**Comment by BramStout** [comment]
I have been able to reproduce this bug and a fix for it will come in the next release.

> Also file selector thingy is looks like from 1994 lol, isn't theres a new file explorer to select these map thingys?

MiEx uses Java Swing for the user interface so that it can run on all versions of Java 8 and up. Java Swing is quite old, so unfortunately things like the file selector do look very old.

**Comment by BramStout** [comment]
This has now been fixed in the latest release, which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.3.0
