### ISSUE TITLE
Grass does not inherit biome colours 

### ISSUE THREAD

**Issue by michal212345** [BramStoutProductions/MiEx#26]
The grass seems to lack Cd
![image](https://github.com/BramStoutProductions/MiEx/assets/20019071/92d91972-e880-4a40-8466-9bbbc7e6d691)

**Comment by BramStout** [comment]
In 1.20.3, they renamed `grass` to `short_grass` and apparently I forgot to update the `base_resource_pack/miex_config.json` file to include `short_grass` in a couple of places. I'll update it in the next release, but you can easily open up the `miex_config.json` in the base_resource_pack and add `short_grass` to the following places: `caveBlocks`, `randomOffset`, `randomYOffset`, `grassColormapBlocks`, and `doubleSided`

**Comment by BramStout** [comment]
This has now been fixed in the latest release, which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.3.0
