### ISSUE TITLE
Modded Wrong Textures

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#30]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/beeffe69-9934-4ca8-8872-5c282749c7bf)
Using 1.3.0 currently and tree textures are not appearing, but the pink grasses are appearing correctly except the tree and the textures of it, have any idea why again?
My file paths;
resources > Regions Unexplored > assets > regions_unexplored > blockstates > all json files i found in the mod that is needed

resources > Regions Unexplored > assets > regions_unexplored > models > block > all json files i found in the mod that is needed

resources > Regions Unexplored > assets > regions_unexplored > textures > block > all png files i found in the mod that is needed

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/94314017-6d39-4f71-8c95-63d3e82964f8)
Also some stairs and textures are literally corrupted, not works on 1.3.0 at all.

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/69e0b698-0656-4fc2-8834-10109b5ff281)
Even log sizes and leaf placement and sizes are COMPLETELY WRONG.

**Comment by Fyoncle** [comment]
> ![image](https://private-user-images.githubusercontent.com/63975256/325985753-69e0b698-0656-4fc2-8834-10109b5ff281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY4OTIsIm5iZiI6MTcxNDEzNjU5MiwicGF0aCI6Ii82Mzk3NTI1Ni8zMjU5ODU3NTMtNjllMGI2OTgtMDY1Ni00ZmMyLTg4MzQtMTAxMDliNWZmMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEzMDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTMzMmRmODk2YjM0MjU0MmFhMGU5ODc3ZjJlZWRjYmU0MmFlMWNiM2YzNzBlNzZiNDA5ODRkMGM0YzkyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gQm97Opgg1Kk13nM_ZZPnGLXsfPzaJ5kBLNccm3gqGY) Even log sizes and leaf placement and sizes are COMPLETELY WRONG.

[i manually putted the textures but didnt work.]

**Comment by BramStout** [comment]
Tomorrow, I'll release a new version that has a tool to automatically extract the resource packs from mods. Hopefully that will fix any issues that you might have with modded worlds.

**Comment by Fyoncle** [comment]
> Tomorrow, I'll release a new version that has a tool to automatically extract the resource packs from mods. Hopefully that will fix any issues that you might have with modded worlds.

Yay!!! that will help A LOT.

**Comment by Fyoncle** [comment]
Camping here for the new version :D

**Comment by BramStout** [comment]
> Camping here for the new version :D

Sorry, it'll be tomorrow!

**Comment by Fyoncle** [comment]
> > Camping here for the new version :D
> 
> Sorry, it'll be tomorrow!

:c

**Comment by Fyoncle** [comment]
CAMPING HERE AGAIN HAHA. 😈

**Comment by Fyoncle** [comment]
Modded worlds now completely black without any logs, i'm using MiEx 1.4.0

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/689b335a-f3c5-4960-9c31-0c866933209c)
BRAM STOUT, THAT IS A MASTERPIECE!!! THANK YOU FOR THE VERSION BRO.

**Comment by Fyoncle** [comment]
> ![image](https://private-user-images.githubusercontent.com/63975256/326268005-689b335a-f3c5-4960-9c31-0c866933209c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTkyNDQsIm5iZiI6MTcxNDMxODk0NCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNjgwMDUtNjg5YjMzNWEtZjNjNS00OTYwLTljMzEtMGM4NjY5MzMyMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE1NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGNhMTRhZTJlMWNjNzNlYTM0Y2UwZGE3ODc1NDExODI4ZWJhYTk0NWUyNjAxNzZkMjExY2ExNTQ4MTI3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNArNZJn9EttRNe-SCT3cmfOgb8Pzd40ekznfBrLN4w) BRAM STOUT, THAT IS A MASTERPIECE!!! THANK YOU FOR THE VERSION BRO.

TESTED WITH MODDED BLOCKS, THEY ALSO WORK!!! ONLY PROBLEM IS ANIMATED TEXTURES BUT ITS FINE.

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/fd60d805-4cdb-4266-8263-e1f29095cb71)

**Comment by Fyoncle** [comment]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/6c60cea1-8753-4ef9-a876-84e0fc94c4b4)
These tree branch textures are not getting exported with MiEx for some reason, i don't know why.

**Comment by BramStout** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63975256/326268005-689b335a-f3c5-4960-9c31-0c866933209c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTkyNDQsIm5iZiI6MTcxNDMxODk0NCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNjgwMDUtNjg5YjMzNWEtZjNjNS00OTYwLTljMzEtMGM4NjY5MzMyMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE1NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGNhMTRhZTJlMWNjNzNlYTM0Y2UwZGE3ODc1NDExODI4ZWJhYTk0NWUyNjAxNzZkMjExY2ExNTQ4MTI3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNArNZJn9EttRNe-SCT3cmfOgb8Pzd40ekznfBrLN4w) BRAM STOUT, THAT IS A MASTERPIECE!!! THANK YOU FOR THE VERSION BRO.
> 
> TESTED WITH MODDED BLOCKS, THEY ALSO WORK!!! ONLY PROBLEM IS ANIMATED TEXTURES BUT ITS FINE.
> 
> ![image](https://private-user-images.githubusercontent.com/63975256/326269980-fd60d805-4cdb-4266-8263-e1f29095cb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjg1MDEsIm5iZiI6MTcxNDMyODIwMSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNjk5ODAtZmQ2MGQ4MDUtNGNkYi00MjY2LTgyNjMtZTFmMjkwOTVjYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZTMwMjcxMDZhNjc3MzE4ODQ0ZDRiNWRkNjlmNGE0YzE1Mjc5NWEwZmNhNGI3NjM2NzMyZmIxNDU2ZjliZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwlTtxg1nfOniCnlZa3TABtdmheYDzwugyNrsHjh0EI)

The animated textures not working, should be because you're using UsdPreviewSurface for the materials. UsdPreviewSurface doesn't support animated textures. But it is on my to-do list to improve compatibility with various DCCs.


> ![image](https://private-user-images.githubusercontent.com/63975256/326278775-6c60cea1-8753-4ef9-a876-84e0fc94c4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjg1MDEsIm5iZiI6MTcxNDMyODIwMSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNzg3NzUtNmM2MGNlYTEtODc1My00ZWY5LWE4NzYtODRlMGZjOTRjNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTQxMzY2YWVjNDg4NTJiNmZlNTAwZDMwNThjZjNhNGU3ODI1OTI0MTkxMDA3YTYzN2EyOWQ4YTRkMzZlNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.friy1FWQM5leSOIBmm_TYq2gCZRh-5qebHgMQxhnav8) These tree branch textures are not getting exported with MiEx for some reason, i don't know why.

It looks like an issue with how MiEx handles resource identifiers for textures specified in model files. Resource identifiers are how you specify different textures, blocks, items, models, etc. Each resource identifier also has a namespace. If no namespace is specified, a namespace is implicitly added in. When I wrote it, I assumed that it would use the namespace of the model file, when no namespace is specified. But, it turns out that Minecraft always uses the "minecraft:" namespace when you don't specify a namespace. I'll get a new version out tomorrow to fix this.

**Comment by Fyoncle** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/63975256/326268005-689b335a-f3c5-4960-9c31-0c866933209c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTkyNDQsIm5iZiI6MTcxNDMxODk0NCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNjgwMDUtNjg5YjMzNWEtZjNjNS00OTYwLTljMzEtMGM4NjY5MzMyMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE1NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGNhMTRhZTJlMWNjNzNlYTM0Y2UwZGE3ODc1NDExODI4ZWJhYTk0NWUyNjAxNzZkMjExY2ExNTQ4MTI3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNArNZJn9EttRNe-SCT3cmfOgb8Pzd40ekznfBrLN4w) BRAM STOUT, THAT IS A MASTERPIECE!!! THANK YOU FOR THE VERSION BRO.
> > 
> > 
> > TESTED WITH MODDED BLOCKS, THEY ALSO WORK!!! ONLY PROBLEM IS ANIMATED TEXTURES BUT ITS FINE.
> > ![image](https://private-user-images.githubusercontent.com/63975256/326269980-fd60d805-4cdb-4266-8263-e1f29095cb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjg1MDEsIm5iZiI6MTcxNDMyODIwMSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNjk5ODAtZmQ2MGQ4MDUtNGNkYi00MjY2LTgyNjMtZTFmMjkwOTVjYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZTMwMjcxMDZhNjc3MzE4ODQ0ZDRiNWRkNjlmNGE0YzE1Mjc5NWEwZmNhNGI3NjM2NzMyZmIxNDU2ZjliZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwlTtxg1nfOniCnlZa3TABtdmheYDzwugyNrsHjh0EI)
> 
> The animated textures not working, should be because you're using UsdPreviewSurface for the materials. UsdPreviewSurface doesn't support animated textures. But it is on my to-do list to improve compatibility with various DCCs.
> 
> > ![image](https://private-user-images.githubusercontent.com/63975256/326278775-6c60cea1-8753-4ef9-a876-84e0fc94c4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjg1MDEsIm5iZiI6MTcxNDMyODIwMSwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNzg3NzUtNmM2MGNlYTEtODc1My00ZWY5LWE4NzYtODRlMGZjOTRjNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTQxMzY2YWVjNDg4NTJiNmZlNTAwZDMwNThjZjNhNGU3ODI1OTI0MTkxMDA3YTYzN2EyOWQ4YTRkMzZlNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.friy1FWQM5leSOIBmm_TYq2gCZRh-5qebHgMQxhnav8) These tree branch textures are not getting exported with MiEx for some reason, i don't know why.
> 
> It looks like an issue with how MiEx handles resource identifiers for textures specified in model files. Resource identifiers are how you specify different textures, blocks, items, models, etc. Each resource identifier also has a namespace. If no namespace is specified, a namespace is implicitly added in. When I wrote it, I assumed that it would use the namespace of the model file, when no namespace is specified. But, it turns out that Minecraft always uses the "minecraft:" namespace when you don't specify a namespace. I'll get a new version out tomorrow to fix this.

Thank you! also my friend making a new addon that will add a compatiblity for animated textures and more into MiEx!

**Comment by BlueEvilGFX** [comment]
> The animated textures not working, should be because you're using UsdPreviewSurface for the materials. UsdPreviewSurface doesn't support animated textures. But it is on my to-do list to improve compatibility with various DCCs.

Hi there :)
Just a small question regarding the animated textures. The values of the time samples / location are correct though? 
`float2 inputs:translation.timeSamples = {...}`. So it would give me the correct result for animating the texture based on the frametime of the animation ingame (translated values of the `.mcmeta` file)? 
Thanks in advance!

**Comment by BramStout** [comment]
> > The animated textures not working, should be because you're using UsdPreviewSurface for the materials. UsdPreviewSurface doesn't support animated textures. But it is on my to-do list to improve compatibility with various DCCs.
> 
> Hi there :) Just a small question regarding the animated textures. The values of the time samples / location are correct though? `float2 inputs:translation.timeSamples = {...}`. So it would give me the correct result for animating the texture based on the frametime of the animation ingame (translated values of the `.mcmeta` file)? Thanks in advance!

The values are indeed translated from the .mcmeta file, so they should be correct. Although, I did recently find out that it might be playing the animation in reverse, so I'll be investigating this tomorrow and will have a fix for it in the next release that is planned for tomorrow

**Comment by BlueEvilGFX** [comment]
> The values are indeed translated from the .mcmeta file, so they should be correct. Although, I did recently find out that it might be playing the animation in reverse, so I'll be investigating this tomorrow and will have a fix for it in the next release that is planned for tomorrow. You can read more about it in this section of the Wiki (the part that talks about expressions): https://github.com/BramStoutProductions/MiEx/wiki/6.-USD#material-templates

Thanks for your quick reply!
So the composed composed `material.usd` file has following for the animation keyframes... 

```
float2 inputs:translation.timeSamples = {
                -0.301: (0.0,0.0),
                -0.3: (0.0,0.96875),
                1.699: (0.0,0.96875),
                1.7: (0.0,0.9375),
                3.699: (0.0,0.9375)...
```

Am i correct that the key are the frames? If so, for which framerate are these? Thanks a bunch, this would help me a lot to have a more precise animation playback speed.

**Comment by BramStout** [comment]
> > The values are indeed translated from the .mcmeta file, so they should be correct. Although, I did recently find out that it might be playing the animation in reverse, so I'll be investigating this tomorrow and will have a fix for it in the next release that is planned for tomorrow. You can read more about it in this section of the Wiki (the part that talks about expressions): https://github.com/BramStoutProductions/MiEx/wiki/6.-USD#material-templates
> 
> Thanks for your quick reply! So the composed composed `material.usd` file has following for the animation keyframes...
> 
> ```
> float2 inputs:translation.timeSamples = {
>                 -0.301: (0.0,0.0),
>                 -0.3: (0.0,0.96875),
>                 1.699: (0.0,0.96875),
>                 1.7: (0.0,0.9375),
>                 3.699: (0.0,0.9375)...
> ```
> 
> Am i correct that the key are the frames? If so, for which framerate are these? Thanks a bunch, this would help me a lot to have a more precise animation playback speed.

The keys are indeed in frames. It doesn't specify the framerate, so it's whatever the framerate of your DCC is. Minecraft's framerate is 20 FPS, so you could say that the implicit framerate of the animation keyframes is 20 FPS. But depending on the framerate of your project, you might want it to be a different speed. So, in the [miex_config.json](https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration-and-Customisations#configurations) file you can specify a frame rate multiplier with the setting `animatedTexturesFrameTimeMultiplier`. The default config file is located in the base_resource_pack, but any resource pack can contain a miex_config.json file allowing you to override specific settings only when specific resource packs are enabled. So you could make a resource pack for if your project is 30 FPS, or 60 FPS, etc. which would just change that one setting.

**Comment by Fyoncle** [comment]
> > > The values are indeed translated from the .mcmeta file, so they should be correct. Although, I did recently find out that it might be playing the animation in reverse, so I'll be investigating this tomorrow and will have a fix for it in the next release that is planned for tomorrow. You can read more about it in this section of the Wiki (the part that talks about expressions): https://github.com/BramStoutProductions/MiEx/wiki/6.-USD#material-templates
> > 
> > 
> > Thanks for your quick reply! So the composed composed `material.usd` file has following for the animation keyframes...
> > ```
> > float2 inputs:translation.timeSamples = {
> >                 -0.301: (0.0,0.0),
> >                 -0.3: (0.0,0.96875),
> >                 1.699: (0.0,0.96875),
> >                 1.7: (0.0,0.9375),
> >                 3.699: (0.0,0.9375)...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am i correct that the key are the frames? If so, for which framerate are these? Thanks a bunch, this would help me a lot to have a more precise animation playback speed.
> 
> The keys are indeed in frames. It doesn't specify the framerate, so it's whatever the framerate of your DCC is. Minecraft's framerate is 20 FPS, so you could say that the implicit framerate of the animation keyframes is 20 FPS. But depending on the framerate of your project, you might want it to be a different speed. So, in the [miex_config.json](https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration-and-Customisations#configurations) file you can specify a frame rate multiplier with the setting `animatedTexturesFrameTimeMultiplier`. The default config file is located in the base_resource_pack, but any resource pack can contain a miex_config.json file allowing you to override specific settings only when specific resource packs are enabled. So you could make a resource pack for if your project is 30 FPS, or 60 FPS, etc. which would just change that one setting.

Hes making an addon for MiEx to add animated textures into blender.

**Comment by BramStout** [comment]
> > > > The values are indeed translated from the .mcmeta file, so they should be correct. Although, I did recently find out that it might be playing the animation in reverse, so I'll be investigating this tomorrow and will have a fix for it in the next release that is planned for tomorrow. You can read more about it in this section of the Wiki (the part that talks about expressions): https://github.com/BramStoutProductions/MiEx/wiki/6.-USD#material-templates
> > > 
> > > 
> > > Thanks for your quick reply! So the composed composed `material.usd` file has following for the animation keyframes...
> > > ```
> > > float2 inputs:translation.timeSamples = {
> > >                 -0.301: (0.0,0.0),
> > >                 -0.3: (0.0,0.96875),
> > >                 1.699: (0.0,0.96875),
> > >                 1.7: (0.0,0.9375),
> > >                 3.699: (0.0,0.9375)...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Am i correct that the key are the frames? If so, for which framerate are these? Thanks a bunch, this would help me a lot to have a more precise animation playback speed.
> > 
> > 
> > The keys are indeed in frames. It doesn't specify the framerate, so it's whatever the framerate of your DCC is. Minecraft's framerate is 20 FPS, so you could say that the implicit framerate of the animation keyframes is 20 FPS. But depending on the framerate of your project, you might want it to be a different speed. So, in the [miex_config.json](https://github.com/BramStoutProductions/MiEx/wiki/3.-Pipeline-Integration-and-Customisations#configurations) file you can specify a frame rate multiplier with the setting `animatedTexturesFrameTimeMultiplier`. The default config file is located in the base_resource_pack, but any resource pack can contain a miex_config.json file allowing you to override specific settings only when specific resource packs are enabled. So you could make a resource pack for if your project is 30 FPS, or 60 FPS, etc. which would just change that one setting.
> 
> Hes making an addon for MiEx to add animated textures into blender, so i think he needs further explanation about how to get how fast animations info from mods and all automatically into the addon.

If he has access to the USD data, then he could take the animation keyframes from the USD export from MiEx and apply it in Blender onto the right shading node. If he doesn't have access to the USD data, then he could look up the file path of the texture and then find the mcmeta file for that texture, read it himself and figure out the animation keyframes from that. Just like MiEx also figures out the animation keyframes from the mcmeta file.

**Comment by BramStout** [comment]
> ![image](https://private-user-images.githubusercontent.com/63975256/326278775-6c60cea1-8753-4ef9-a876-84e0fc94c4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTU1NDgsIm5iZiI6MTcxNDQxNTI0OCwicGF0aCI6Ii82Mzk3NTI1Ni8zMjYyNzg3NzUtNmM2MGNlYTEtODc1My00ZWY5LWE4NzYtODRlMGZjOTRjNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE4MjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1M2MxN2Q0NjY0NTE3MmE5OGMwNDhiNTlhMzE3ZDRiZTVmOWY0Y2E4MzI2Yjc0ZTZjN2FlYzFkZDM3ZTY4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6t9dXWwJ7BGeyEtFxSTizH8FX7wxOBBkwil7f5Umh8c) These tree branch textures are not getting exported with MiEx for some reason, i don't know why.

This issue has now been fixed in the latest release of MiEx, which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.5.0
