### ISSUE TITLE
Huge Worlds Problem

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#31]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/7251e7ec-60c8-4914-b8a6-061c4f35a89a)

MiEx Exporting the worlds into blender in a huge size that every single rig is so small compared to world.
And that results in without increasing camera clip, we cannot see the world in blender.

**Comment by michal212345** [comment]
You can just scale them down in blender to what you need them to be

**Comment by BramStout** [comment]
MiEx exports out worlds where one block is 16x16x16 units. Tomorrow I'll release a new version which will have a setting in the `miex_config.json` to change this scale.
