### ISSUE TITLE
Optional Core Usage

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#37]
So you said it uses all my pc cores when exporting a world, well when i was exporting a HUGE world about 5000 chunks, it literally slowed down a lot and my pc was about to blue screen, and it didnt get fixed for like 20 minutes even tho my pc not bad, will there be future like "Multiple Core Usage" checkmark so i can actually render the world slower but without hurting my computer insanely overloaded by a world export.

**Comment by BramStout** [comment]
I'll add in a setting to tell MiEx to leave a certain number of cores alone.

**Comment by BramStout** [comment]
MiEx will now leave four threads over for the rest of your computer by default and you can change this number using the `MIEX_NUM_UI_THREADS` environment variable or `-numUIThreads <number>` command-line argument.

You can get the latest release with this improvement here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.5.0
