### ISSUE TITLE
MiEx errors out on Linux Systems, Even with a Specified Path

### ISSUE THREAD

**Issue by StandingPadAnimations** [BramStoutProductions/MiEx#40]
When running MiEx with a specified directory for a Flatpak install of PrismMC, it ends up ignoring what I pass:
```
$ java -jar MiEx.jar -multimcRootDir "/home/mahid/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher"
Installing base_resource_pack
java.lang.RuntimeException: Could not find minecraft directory
        at nl.bramstout.mcworldexporter.FileUtil.getMinecraftRootDir(FileUtil.java:167)
        at nl.bramstout.mcworldexporter.FileUtil.getMinecraftVersionsDir(FileUtil.java:178)
        at nl.bramstout.mcworldexporter.resourcepack.ResourcePack.updateBaseResourcePack(ResourcePack.java:346)
        at nl.bramstout.mcworldexporter.resourcepack.ResourcePack.setupDefaults(ResourcePack.java:241)
        at nl.bramstout.mcworldexporter.MCWorldExporter.<init>(MCWorldExporter.java:83)
        at nl.bramstout.mcworldexporter.MCWorldExporter.main(MCWorldExporter.java:199)
```

Checking the code for `updateBaseResourcePack`, I see that what should be called is `getMultiMCRootDir`, but instead it's calling `getMinecraftVersionsDir` and erroring out. [From what I can tell](https://github.com/BramStoutProductions/MiEx/blob/c117907be8e1d61e19be3f69deca35f3b5c84a70/src/nl/bramstout/mcworldexporter/FileUtil.java#L163-L167), `getMinecraftVersionsDir` only tests for Windows and macOS, but not Linux, so when it can't find `.minecraft` in the Windows and macOS paths, it errors out. 

As a programmer myself, there are a couple of things I think could be done to resolve this:
- Add `~/.config/.minecraft` (`~` is short for `/home/user`) to the search paths (Linux is officially supported by Mojang)
- Return some placeholder value in the case of an error (speaking from experience, this would be some special error object returned by the function that the caller can then handle however they wish)
	- This would account for other operating systems like the BSD family, and avoid users on niche operating systems from dealing with errors (most users on niche systems would probably use environment variables/CLI arguments anyway)

Further details: 
- OS: Arch Linux
- JRE (output of `java --version`): `openjdk 22 2024-03-19`
- MiEx version: [`v1.4.0`](https://github.com/BramStoutProductions/MiEx/releases/tag/v1.4.0)

**Comment by BramStout** [comment]
The pull request that you created fixing this issue, has been included in the latest release which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.5.0
