### ISSUE TITLE
Mouse Hover LOD Reset

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#52]
When mouse is hovered over the LOD checkmark or the text, LOD's that selected with shift is completely resets itself into the past position.

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/43e3fc77-67fe-4690-80f3-7f0a57c1cc7a)

**Comment by BramStout** [comment]
Thank you for sending in this bug report! I have been able to reproduce this bug and it will be fixed in the next release.

**Comment by Fyoncle** [comment]
> Thank you for sending in this bug report! I have been able to reproduce this bug and it will be fixed in the next release.

You're welcome!

**Comment by BramStout** [comment]
This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0
