### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#53]
Refresh Button definetely required for the resource packs.

And if possible, even a texture preview system on MiEx so we can test the resource pack if works or not instead of 1000 times exporting to blender because solid color change on the MiEx not completely enough to see a difference.

**Comment by BramStout** [comment]
A refresh button has been added to MiEx. You can get the latest version with this button here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0
