### ISSUE TITLE
Connected Textures Not Working

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#54]
None of the connected textures mod working, if we need to give names, [Continuity](https://modrinth.com/mod/continuity), [Fusion](https://modrinth.com/mod/fusion-connected-textures), [CTM](https://www.curseforge.com/minecraft/mc-mods/ctm), [Athena](https://modrinth.com/mod/athena-ctm) doesn't work, i would like a support!

**Comment by zNightlord** [comment]
I would say this would be one of those painful task. *sweats*
Because you have to deal with many ctm methods beside standard original from Optifine, CTM above ChiselTeam (Chisel mod) is another one with different set of methods.

**Comment by BramStout** [comment]
Support for connected textures has now been added to MiEx. It currently only supports Optifine's CTM format.

You can get the latest version of MiEx with this feature here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0

**Comment by Fyoncle** [comment]
> Support for connected textures has now been added to MiEx. It currently only supports Optifine's CTM format.
> 
> You can get the latest version of MiEx with this feature here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0

I HATE OPTIFINE, WHY NOT CONTINUITY :(

**Comment by BramStout** [comment]
> > Support for connected textures has now been added to MiEx. It currently only supports Optifine's CTM format.
> > You can get the latest version of MiEx with this feature here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0
> 
> I HATE OPTIFINE, WHY NOT CONTINUITY :(

Continuity uses the same Optifine CTM format. So, resource packs that work with Continuity also work with Optifine and thus with MiEx.

**Comment by PixusPanic** [comment]
> Support for connected textures has now been added to MiEx. It currently only supports Optifine's CTM format.
> 
> You can get the latest version of MiEx with this feature here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0

I really want to say that I greatly appreciate you putting in the time to put in this suggestion! As someone who loves building structures that use modded blocks, I think this is going to be very handy with my workflow. Don't stress yourself, and keep up the great work!
