### ISSUE TITLE
Biome Colors & Resource Pack Mix

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#55]
Not sure if its a MiEx or BlueEvil's addon problem, but when i try to prep this world with BlueEvil's addon;
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/483b7883-f6b7-4d7e-8a6a-0ea7f98b065d)
Which should look like that in biome colors;
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/04609023-9210-4e94-8527-c93e075349cd)
But instead it looks like that;
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/5e5c388b-36cf-433e-b19d-3d79b268303c)

**Comment by BramStout** [comment]
This could be a render gamut thing. Render engines can use different colour spaces to do all of the rendering in. Textures automatically get converted into the colour space used for rendering, but vertex colours are assumed to already be in that colour space. MiEx uses vertex colours for the biome colours, and so MiEx needs to export those biome colours out into the colour space that you use for rendering in your animation program.

By default, MiEx assumes that this colour space is ACEScg, since ACES is often the default colour management workflow used in most animation softwares and render engines. Blender uses the linear-sRGB / linear-Rec.709 colour space for rendering by default. This can cause the colours to show up differently. You can fix this by going into `resources/base_resource_pack/miex_config.json` and change `"renderGamut": "ACEScg",` into `"renderGamut": "sRGB",`

For the next release, MiEx will get an update to the material templating system which will then allow us to update the Blender addon. With that updated Blender addon will also come a new resource pack specifically for Blender. In that new resource pack, we'll make sure to automatically set the renderGamut to sRGB, so that the colours will be correct by default.

**Comment by Fyoncle** [comment]
> This could be a render gamut thing. Render engines can use different colour spaces to do all of the rendering in. Textures automatically get converted into the colour space used for rendering, but vertex colours are assumed to already be in that colour space. MiEx uses vertex colours for the biome colours, and so MiEx needs to export those biome colours out into the colour space that you use for rendering in your animation program.
> 
> By default, MiEx assumes that this colour space is ACEScg, since ACES is often the default colour management workflow used in most animation softwares and render engines. Blender uses the linear-sRGB / linear-Rec.709 colour space for rendering by default. This can cause the colours to show up differently. You can fix this by going into `resources/base_resource_pack/miex_config.json` and change `"renderGamut": "ACEScg",` into `"renderGamut": "sRGB",`
> 
> For the next release, MiEx will get an update to the material templating system which will then allow us to update the Blender addon. With that updated Blender addon will also come a new resource pack specifically for Blender. In that new resource pack, we'll make sure to automatically set the renderGamut to sRGB, so that the colours will be correct by default.

I understand what you're trying to say, but i already use sRGB, and even tho i tried swapping color management templates on blender, its still on the wrong color.

**Comment by BramStout** [comment]
> > This could be a render gamut thing. Render engines can use different colour spaces to do all of the rendering in. Textures automatically get converted into the colour space used for rendering, but vertex colours are assumed to already be in that colour space. MiEx uses vertex colours for the biome colours, and so MiEx needs to export those biome colours out into the colour space that you use for rendering in your animation program.
> > By default, MiEx assumes that this colour space is ACEScg, since ACES is often the default colour management workflow used in most animation softwares and render engines. Blender uses the linear-sRGB / linear-Rec.709 colour space for rendering by default. This can cause the colours to show up differently. You can fix this by going into `resources/base_resource_pack/miex_config.json` and change `"renderGamut": "ACEScg",` into `"renderGamut": "sRGB",`
> > For the next release, MiEx will get an update to the material templating system which will then allow us to update the Blender addon. With that updated Blender addon will also come a new resource pack specifically for Blender. In that new resource pack, we'll make sure to automatically set the renderGamut to sRGB, so that the colours will be correct by default.
> 
> I understand what you're trying to say, but i already use sRGB, and even tho i tried swapping color management templates on blender, its still on the wrong color.

Just to clarify, the `renderGamut` setting in MiEx (not Blender) is already sRGB?

**Comment by Fyoncle** [comment]
Nope, my bad your good, ill wait for the next release.

**Comment by Fyoncle** [comment]
> > > This could be a render gamut thing. Render engines can use different colour spaces to do all of the rendering in. Textures automatically get converted into the colour space used for rendering, but vertex colours are assumed to already be in that colour space. MiEx uses vertex colours for the biome colours, and so MiEx needs to export those biome colours out into the colour space that you use for rendering in your animation program.
> > > By default, MiEx assumes that this colour space is ACEScg, since ACES is often the default colour management workflow used in most animation softwares and render engines. Blender uses the linear-sRGB / linear-Rec.709 colour space for rendering by default. This can cause the colours to show up differently. You can fix this by going into `resources/base_resource_pack/miex_config.json` and change `"renderGamut": "ACEScg",` into `"renderGamut": "sRGB",`
> > > For the next release, MiEx will get an update to the material templating system which will then allow us to update the Blender addon. With that updated Blender addon will also come a new resource pack specifically for Blender. In that new resource pack, we'll make sure to automatically set the renderGamut to sRGB, so that the colours will be correct by default.
> > 
> > 
> > I understand what you're trying to say, but i already use sRGB, and even tho i tried swapping color management templates on blender, its still on the wrong color.
> 
> Just to clarify, the `renderGamut` setting in MiEx (not Blender) is already sRGB?

![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/769b5292-12ce-4301-97e0-73dc0e2ac69c)
Yes i tried sRGB too and it didn't fix.

**Comment by BramStout** [comment]
I have looked into it and I think I've found out what's going on. MiEx does export everything out correctly and BlueEvil's addon also works correctly, instead Minecraft has a post-process filter that increases the saturation.

I did a test to verify this. Here's a screenshot of both Minecraft, Maya, and Maya's viewport but with increased saturation in Photoshop: 

![Image](https://github.com/BramStoutProductions/MiEx/assets/128681226/28c2a13b-87ff-4478-8863-45c49ecc17f9)

Simply increasing the saturation causes it to match. Because this is a post-process filter applied by Minecraft, which gets applied on everything, it's out of the scope of MiEx (there wouldn't be any good way to get this in MiEx, you really have to do it afterwards during compositing as a colour grade). Next to that, it's common to have a colour rendering applied (like from ACES or AgX) which often adds some contrast to the image which results in an increase of saturation already. 

Another thing to potentially look at is that if materials have specular turned on, then that can cause a desaturation as well. Looking at your screenshot, it does seem like there is some specularity being shown.

**Comment by Fyoncle** [comment]
> I have looked into it and I think I've found out what's going on. MiEx does export everything out correctly and BlueEvil's addon also works correctly, instead Minecraft has a post-process filter that increases the saturation.
> 
> I did a test to verify this. Here's a screenshot of both Minecraft, Maya, and Maya's viewport but with increased saturation in Photoshop:
> 
> ![Image](https://private-user-images.githubusercontent.com/128681226/328926934-28c2a13b-87ff-4478-8863-45c49ecc17f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzkxNTksIm5iZiI6MTcxNTE3ODg1OSwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTI2OTM0LTI4YzJhMTNiLTg3ZmYtNDQ3OC04ODYzLTQ1YzQ5ZWNjMTdmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNDM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2UxZWQwNzJhNjYzYjI5YmU1ODRmNjNlMDQ2N2NmNjFlZWY0YzYxNmUwMzNjZjZkZGYzYjJiMzU4N2UyYzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KbtCjDtAGcjlrtKurQS9Q31lkrErlCq3broZt7hBaTE)
> 
> Simply increasing the saturation causes it to match. Because this is a post-process filter applied by Minecraft, which gets applied on everything, it's out of the scope of MiEx (there wouldn't be any good way to get this in MiEx, you really have to do it afterwards during compositing as a colour grade). Next to that, it's common to have a colour rendering applied (like from ACES or AgX) which often adds some contrast to the image which results in an increase of saturation already.
> 
> Another thing to potentially look at is that if materials have specular turned on, then that can cause a desaturation as well. Looking at your screenshot, it does seem like there is some specularity being shown.

No specularity there its just a illusion of viewport.

**Comment by BramStout** [comment]
> > I have looked into it and I think I've found out what's going on. MiEx does export everything out correctly and BlueEvil's addon also works correctly, instead Minecraft has a post-process filter that increases the saturation.
> > I did a test to verify this. Here's a screenshot of both Minecraft, Maya, and Maya's viewport but with increased saturation in Photoshop:
> > ![Image](https://private-user-images.githubusercontent.com/128681226/328926934-28c2a13b-87ff-4478-8863-45c49ecc17f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzkxNTksIm5iZiI6MTcxNTE3ODg1OSwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTI2OTM0LTI4YzJhMTNiLTg3ZmYtNDQ3OC04ODYzLTQ1YzQ5ZWNjMTdmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNDM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2UxZWQwNzJhNjYzYjI5YmU1ODRmNjNlMDQ2N2NmNjFlZWY0YzYxNmUwMzNjZjZkZGYzYjJiMzU4N2UyYzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KbtCjDtAGcjlrtKurQS9Q31lkrErlCq3broZt7hBaTE)
> > Simply increasing the saturation causes it to match. Because this is a post-process filter applied by Minecraft, which gets applied on everything, it's out of the scope of MiEx (there wouldn't be any good way to get this in MiEx, you really have to do it afterwards during compositing as a colour grade). Next to that, it's common to have a colour rendering applied (like from ACES or AgX) which often adds some contrast to the image which results in an increase of saturation already.
> > Another thing to potentially look at is that if materials have specular turned on, then that can cause a desaturation as well. Looking at your screenshot, it does seem like there is some specularity being shown.
> 
> No specularity there its just a illusion of viewport, blueevil's addon is already fixes that.

In that case, the difference that you're seeing should simply be due to Minecraft applying a post-process filter that increases the saturation, which you can achieve as well during compositing.

**Comment by Fyoncle** [comment]
> > > I have looked into it and I think I've found out what's going on. MiEx does export everything out correctly and BlueEvil's addon also works correctly, instead Minecraft has a post-process filter that increases the saturation.
> > > I did a test to verify this. Here's a screenshot of both Minecraft, Maya, and Maya's viewport but with increased saturation in Photoshop:
> > > ![Image](https://private-user-images.githubusercontent.com/128681226/328926934-28c2a13b-87ff-4478-8863-45c49ecc17f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzkxNTksIm5iZiI6MTcxNTE3ODg1OSwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTI2OTM0LTI4YzJhMTNiLTg3ZmYtNDQ3OC04ODYzLTQ1YzQ5ZWNjMTdmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNDM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2UxZWQwNzJhNjYzYjI5YmU1ODRmNjNlMDQ2N2NmNjFlZWY0YzYxNmUwMzNjZjZkZGYzYjJiMzU4N2UyYzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KbtCjDtAGcjlrtKurQS9Q31lkrErlCq3broZt7hBaTE)
> > > Simply increasing the saturation causes it to match. Because this is a post-process filter applied by Minecraft, which gets applied on everything, it's out of the scope of MiEx (there wouldn't be any good way to get this in MiEx, you really have to do it afterwards during compositing as a colour grade). Next to that, it's common to have a colour rendering applied (like from ACES or AgX) which often adds some contrast to the image which results in an increase of saturation already.
> > > Another thing to potentially look at is that if materials have specular turned on, then that can cause a desaturation as well. Looking at your screenshot, it does seem like there is some specularity being shown.
> > 
> > 
> > No specularity there its just a illusion of viewport, blueevil's addon is already fixes that.
> 
> In that case, the difference that you're seeing should simply be due to Minecraft applying a post-process filter that increases the saturation, which you can achieve as well during compositing.

Thanks then!
