### ISSUE TITLE
I can't launch MiEx

### ISSUE THREAD

**Issue by Aspirata** [BramStoutProductions/MiEx#56]
Well, i don't have any idea why i can't launch it. The info below may help.

**OS**: Windows 11
**Java**: I have jdk 17 and java 8

**Comment by StandingPadAnimations** [comment]
What happens if you run `java -jar MiEx.jar`

**Comment by Aspirata** [comment]
Thanks ! I ran D:\Arc>MiEx.jar and it worked. Tho i still can't launch it with double click
