### ISSUE TITLE
Wrong Leaves Color

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#60]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/58be3904-d275-4393-ba5e-00d886600d1c)

When all the other leaves got their color, an birch leaves with resource pack doesn't get its color, i use Stay True resource pack with terralith mod.

**Comment by BramStout** [comment]
After looking at the Stay True resource pack, it looks to me like MiEx is applying the wrong texture. The Stay True resource pack has its own birch leaves texture which is already tinted, but it's grabbing the texture from the base resource pack.

I can currently only think of two reasons: there is another resource pack that overrides the birch leaves texture of the Stay True resource pack (probably not the case), or you are using atlases and MiEx gets it a bit wrong (probably the case).

If you've created an atlas for the base_resource_pack that includes the birch leaves texture, then when it encounters a model with that texture, it swaps it out for the atlas. Now, if you enable the Stay True resource pack, which overrides the birch leaves texture, then MiEx will still swap it out for the atlas (which contains the wrong birch leaves texture) and so you get the result that you're getting. 

This is an issue with MiEx not keeping track that the birch leaves texture got overriden and shouldn't be using the atlas for it. I've added this to my to-do list to fix it. For now, what you can do is use the atlas creator tool on the Stay True resource pack to have it create atlases for that. Those will then properly override the base_resource_pack atlases and you'll get the proper results. There was a bug a little bit ago when having multiple resource packs with atlases, but that has been fixed, so you can freely create atlases for the Stay True resource pack. In the next release of MiEx, I'll have this issue fixed.

**Comment by Fyoncle** [comment]
> After looking at the Stay True resource pack, it looks to me like MiEx is applying the wrong texture. The Stay True resource pack has its own birch leaves texture which is already tinted, but it's grabbing the texture from the base resource pack.
> 
> I can currently only think of two reasons: there is another resource pack that overrides the birch leaves texture of the Stay True resource pack (probably not the case), or you are using atlases and MiEx gets it a bit wrong (probably the case).
> 
> If you've created an atlas for the base_resource_pack that includes the birch leaves texture, then when it encounters a model with that texture, it swaps it out for the atlas. Now, if you enable the Stay True resource pack, which overrides the birch leaves texture, then MiEx will still swap it out for the atlas (which contains the wrong birch leaves texture) and so you get the result that you're getting.
> 
> This is an issue with MiEx not keeping track that the birch leaves texture got overriden and shouldn't be using the atlas for it. I've added this to my to-do list to fix it. For now, what you can do is use the atlas creator tool on the Stay True resource pack to have it create atlases for that. Those will then properly override the base_resource_pack atlases and you'll get the proper results. There was a bug a little bit ago when having multiple resource packs with atlases, but that has been fixed, so you can freely create atlases for the Stay True resource pack. In the next release of MiEx, I'll have this issue fixed.

I didn't created any atlas.

**Comment by BramStout** [comment]
> > After looking at the Stay True resource pack, it looks to me like MiEx is applying the wrong texture. The Stay True resource pack has its own birch leaves texture which is already tinted, but it's grabbing the texture from the base resource pack.
> > I can currently only think of two reasons: there is another resource pack that overrides the birch leaves texture of the Stay True resource pack (probably not the case), or you are using atlases and MiEx gets it a bit wrong (probably the case).
> > If you've created an atlas for the base_resource_pack that includes the birch leaves texture, then when it encounters a model with that texture, it swaps it out for the atlas. Now, if you enable the Stay True resource pack, which overrides the birch leaves texture, then MiEx will still swap it out for the atlas (which contains the wrong birch leaves texture) and so you get the result that you're getting.
> > This is an issue with MiEx not keeping track that the birch leaves texture got overriden and shouldn't be using the atlas for it. I've added this to my to-do list to fix it. For now, what you can do is use the atlas creator tool on the Stay True resource pack to have it create atlases for that. Those will then properly override the base_resource_pack atlases and you'll get the proper results. There was a bug a little bit ago when having multiple resource packs with atlases, but that has been fixed, so you can freely create atlases for the Stay True resource pack. In the next release of MiEx, I'll have this issue fixed.
> 
> I didn't created any atlas so its probably not caused by that, anyways thank you!

I would check the `resources/base_resource_pack` folder for a file called `miex_atlas.json`. If that exists, then atlases were created for it at some point and MiEx will use those. You can simply delete that file to get rid of atlases for it, if you want to. You could also decide to create atlases for the Stay True resource pack, like I described in my comment above.

**Comment by Fyoncle** [comment]
> > > After looking at the Stay True resource pack, it looks to me like MiEx is applying the wrong texture. The Stay True resource pack has its own birch leaves texture which is already tinted, but it's grabbing the texture from the base resource pack.
> > > I can currently only think of two reasons: there is another resource pack that overrides the birch leaves texture of the Stay True resource pack (probably not the case), or you are using atlases and MiEx gets it a bit wrong (probably the case).
> > > If you've created an atlas for the base_resource_pack that includes the birch leaves texture, then when it encounters a model with that texture, it swaps it out for the atlas. Now, if you enable the Stay True resource pack, which overrides the birch leaves texture, then MiEx will still swap it out for the atlas (which contains the wrong birch leaves texture) and so you get the result that you're getting.
> > > This is an issue with MiEx not keeping track that the birch leaves texture got overriden and shouldn't be using the atlas for it. I've added this to my to-do list to fix it. For now, what you can do is use the atlas creator tool on the Stay True resource pack to have it create atlases for that. Those will then properly override the base_resource_pack atlases and you'll get the proper results. There was a bug a little bit ago when having multiple resource packs with atlases, but that has been fixed, so you can freely create atlases for the Stay True resource pack. In the next release of MiEx, I'll have this issue fixed.
> > 
> > 
> > I didn't created any atlas so its probably not caused by that, anyways thank you!
> 
> I would check the `resources/base_resource_pack` folder for a file called `miex_atlas.json`. If that exists, then atlases were created for it at some point and MiEx will use those. You can simply delete that file to get rid of atlases for it, if you want to. You could also decide to create atlases for the Stay True resource pack, like I described in my comment above.

Nope this json is not here, also yea i better wait for the update u gonna do.

**Comment by Fyoncle** [comment]
BramStout, when the update?

**Comment by BramStout** [comment]
> BramStout, when 1.5.2 coming??

I was sick last week, so I've been working hard this week on catching up with all of the things to do. Hopefully, the next version will be released today or tomorrow!

**Comment by BramStout** [comment]
I have just tried the latest version of the Stay True resource pack (version 1.20.4) in the latest, soon to be released, version of MiEx and the birch leaves show up correctly. 
![image](https://github.com/BramStoutProductions/MiEx/assets/128681226/54ad82ac-cc84-44f8-9755-025f8fb5121c)

The new version of MiEx will be released tomorrow, so when it gets released, would you be able to try again (and make sure you're also using the latest version of the Stay True resource pack)?

**Comment by Fyoncle** [comment]
> I have just tried the latest version of the Stay True resource pack (version 1.20.4) in the latest, soon to be released, version of MiEx and the birch leaves show up correctly. ![image](https://private-user-images.githubusercontent.com/128681226/328917320-54ad82ac-cc84-44f8-9755-025f8fb5121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA2MDgsIm5iZiI6MTcxNTM0MDMwOCwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTE3MzIwLTU0YWQ4MmFjLWNjODQtNDRmOC05NzU1LTAyNWY4ZmI1MTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmM0MGM2OGIyN2U5NWUyNjUxMzIyYmI3ZDBjNzMzNTJiNTBlNDQ4NzA4OGVkNjE3ODgwNDMzOTM0YTQyMTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GR3qvFJJkAOpDDD9TZIbfg9C2quxydE7ggcJMT444OU)
> 
> The new version of MiEx will be released tomorrow, so when it gets released, would you be able to try again (and make sure you're also using the latest version of the Stay True resource pack)?

Sure! but where?

**Comment by Fyoncle** [comment]
> > > I have just tried the latest version of the Stay True resource pack (version 1.20.4) in the latest, soon to be released, version of MiEx and the birch leaves show up correctly. ![image](https://private-user-images.githubusercontent.com/128681226/328917320-54ad82ac-cc84-44f8-9755-025f8fb5121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA2MDgsIm5iZiI6MTcxNTM0MDMwOCwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTE3MzIwLTU0YWQ4MmFjLWNjODQtNDRmOC05NzU1LTAyNWY4ZmI1MTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmM0MGM2OGIyN2U5NWUyNjUxMzIyYmI3ZDBjNzMzNTJiNTBlNDQ4NzA4OGVkNjE3ODgwNDMzOTM0YTQyMTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GR3qvFJJkAOpDDD9TZIbfg9C2quxydE7ggcJMT444OU)
> > > The new version of MiEx will be released tomorrow, so when it gets released, would you be able to try again (and make sure you're also using the latest version of the Stay True resource pack)?
> > 
> > 
> > Sure! but wheres the new version lol
> 
> It took a bit longer to get support for connected textures, but it's all done now. I'm now going through the wiki to update it and then I'll upload the new version. It should be uploaded in the next couple of hours.

Woah! you're so talented :D

**Comment by BramStout** [comment]
> > > > I have just tried the latest version of the Stay True resource pack (version 1.20.4) in the latest, soon to be released, version of MiEx and the birch leaves show up correctly. ![image](https://private-user-images.githubusercontent.com/128681226/328917320-54ad82ac-cc84-44f8-9755-025f8fb5121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA2MDgsIm5iZiI6MTcxNTM0MDMwOCwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTE3MzIwLTU0YWQ4MmFjLWNjODQtNDRmOC05NzU1LTAyNWY4ZmI1MTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmM0MGM2OGIyN2U5NWUyNjUxMzIyYmI3ZDBjNzMzNTJiNTBlNDQ4NzA4OGVkNjE3ODgwNDMzOTM0YTQyMTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GR3qvFJJkAOpDDD9TZIbfg9C2quxydE7ggcJMT444OU)
> > > > The new version of MiEx will be released tomorrow, so when it gets released, would you be able to try again (and make sure you're also using the latest version of the Stay True resource pack)?
> > > 
> > > 
> > > Sure! but wheres the new version lol
> > 
> > 
> > It took a bit longer to get support for connected textures, but it's all done now. I'm now going through the wiki to update it and then I'll upload the new version. It should be uploaded in the next couple of hours.
> 
> Woah! you're so talented :D

Here is the latest version: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0

**Comment by Fyoncle** [comment]
> > > > > I have just tried the latest version of the Stay True resource pack (version 1.20.4) in the latest, soon to be released, version of MiEx and the birch leaves show up correctly. ![image](https://private-user-images.githubusercontent.com/128681226/328917320-54ad82ac-cc84-44f8-9755-025f8fb5121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA2MDgsIm5iZiI6MTcxNTM0MDMwOCwicGF0aCI6Ii8xMjg2ODEyMjYvMzI4OTE3MzIwLTU0YWQ4MmFjLWNjODQtNDRmOC05NzU1LTAyNWY4ZmI1MTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmM0MGM2OGIyN2U5NWUyNjUxMzIyYmI3ZDBjNzMzNTJiNTBlNDQ4NzA4OGVkNjE3ODgwNDMzOTM0YTQyMTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GR3qvFJJkAOpDDD9TZIbfg9C2quxydE7ggcJMT444OU)
> > > > > The new version of MiEx will be released tomorrow, so when it gets released, would you be able to try again (and make sure you're also using the latest version of the Stay True resource pack)?
> > > > 
> > > > 
> > > > Sure! but wheres the new version lol
> > > 
> > > 
> > > It took a bit longer to get support for connected textures, but it's all done now. I'm now going through the wiki to update it and then I'll upload the new version. It should be uploaded in the next couple of hours.
> > 
> > 
> > Woah! you're so talented :D
> 
> Here is the latest version: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.0

How are you so talented and working so hard on this, my endless respects! 🔥🔥
