### ISSUE TITLE
LOD Being cubic

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#62]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/e4030ae2-c918-4ffe-b3d7-f793958c1ecb)
Yea i talked about this before but its really weird since LOD only adds more blocks with more cursed shapes and doesn't fix ANY LAG AT ALL! is there any fix for that

**Comment by zNightlord** [comment]
This is more software specific, if you are talking about Blender then you have to know how to modify, tell the usd file who is in charged.

**Comment by BramStout** [comment]
The LOD system doesn't add blocks. It reduces the resolution of the world, so instead of having a group of 4x4x4 blocks, it only has a single block that it then scales by 4 times. When scaling it up, it does repeat the texture to make less obvious that it's just a single block being scaled up to represent 4x4x4 blocks, but if you look at the wire frame then you can see that. 

Could you share the exported USD files and the Blender file with the world imported in? Then I can open it up on my computer to try to see where the lag is coming from.

**Comment by BramStout** [comment]
I have just tried exporting a world from the Elysium Days modpack and importing it into Blender. I'm not getting any lag. Even rendering in Cycles on the CPU is pretty responsive.

https://github.com/BramStoutProductions/MiEx/assets/128681226/0c6d47e9-be05-4ae6-a9da-a4145544c48c

One thing that could cause things to slow down is the amount of materials. Modded worlds often have lots of materials and especially when combined with connected textures. Blender can struggle with all of those materials. You can reduce the amount of materials by using atlases. In MiEx you have the Atlas Creator tool that allows you to create atlases from resource packs. You can read more about the Atlas Creator tool [here.](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#atlas-creator-tool)

Also, the LOD system is meant to reduce complexity for the far background where you're not going to notice the changes. It's not meant to be used for the foreground of the set.

**Comment by Fyoncle** [comment]
> I have just tried exporting a world from the Elysium Days modpack and importing it into Blender. I'm not getting any lag. Even rendering in Cycles on the CPU is pretty responsive.
> 
>  Miex_Blender_Lag2.mp4 
> One thing that could cause things to slow down is the amount of materials. Modded worlds often have lots of materials and especially when combined with connected textures. Blender can struggle with all of those materials. You can reduce the amount of materials by using atlases. In MiEx you have the Atlas Creator tool that allows you to create atlases from resource packs. You can read more about the Atlas Creator tool [here.](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#atlas-creator-tool)
> 
> Also, the LOD system is meant to reduce complexity for the far background where you're not going to notice the changes. It's not meant to be used for the foreground of the set.

That is small world as hell, im talking about insanely huge worlds, specially more than 4000x4000 or bigger, the lod just doesnt help the lag but instead my pc freezing, my cpu getting in overload, blender freezing so much often, i cannot get in edit mode with selecting all the world. Anddd more painful things

**Comment by BramStout** [comment]
> > I have just tried exporting a world from the Elysium Days modpack and importing it into Blender. I'm not getting any lag. Even rendering in Cycles on the CPU is pretty responsive.
> > Miex_Blender_Lag2.mp4
> > One thing that could cause things to slow down is the amount of materials. Modded worlds often have lots of materials and especially when combined with connected textures. Blender can struggle with all of those materials. You can reduce the amount of materials by using atlases. In MiEx you have the Atlas Creator tool that allows you to create atlases from resource packs. You can read more about the Atlas Creator tool [here.](https://github.com/BramStoutProductions/MiEx/wiki/4.-Resource-Packs#atlas-creator-tool)
> > Also, the LOD system is meant to reduce complexity for the far background where you're not going to notice the changes. It's not meant to be used for the foreground of the set.
> 
> That is small world as hell, im talking about insanely huge worlds, specially more than 4000x4000 or bigger, the lod just doesnt help the lag but instead my pc freezing, my cpu getting in overload, blender freezing so much often, i cannot get in edit mode with selecting all the world. Anddd more painful things

I have added a section to the Wiki with tips for exporting large worlds. With these tips in mind, I was able to import in a 5000x5000 block world into Blender without lag.

You can find the section here: https://github.com/BramStoutProductions/MiEx/wiki/8.-Importing-into-DCCs#very-large-worlds
