### ISSUE TITLE
Specular Textures [BlueEvil's Addon]

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#63]
Specular getting set to 0.5 even tho it meant to be 0 when i prep the world with blueevil's addon.

**Comment by zNightlord** [comment]
[principled](https://github.com/BramStoutProductions/MiEx/blob/6c3a6ef32a91be18b998405c907044e81727a2e1/extras/Blender/BlenderAddon/MiEx_helper.py#L199)
Go to the addon and add under that line in the meantime.

4.0+
>	bsdf_node.inputs["Specular IOR Level"].default_value = 0
3.6
> bsdf_node.inputs["Specular"].default_value = 0

**Comment by StandingPadAnimations** [comment]
> Specular getting set to 0.5 even tho it meant to be 0 when i prep the world with blueevil's addon.

That's the default for Principled BSDF

**Comment by BramStout** [comment]
MiEx now has a new Blender addon that fixes this issue. The new Blender addon imports in the materials exported out from MiEx, which themselves are generated from the material templates. The repository also contains an example resource pack specifically for Blender which has specular turned off by default.

You can read more about the new Blender addon here: https://github.com/BramStoutProductions/MiEx/wiki/8.-Importing-into-DCCs#blender
