### ISSUE TITLE
Modded Dimensions Blocked

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#65]
Modded Dimensions are not allowed to teleport to via the TP button in the gui, or either to choose via dropdown.

**Comment by BramStout** [comment]
With what modpack are you trying this?

**Comment by Fyoncle** [comment]
> With what modpack are you trying this?

My modpack, called Elysium Days and its on modrinth, although the dimension im trying is "Deeper And Darker" dimension, and im sure other modded dimensions also blocked.

**Comment by BramStout** [comment]
This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.1
