### ISSUE TITLE
Lod Open & Close Reset

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#67]
When you enable the lod and select somewhere then close it, it resets the whole position you selected, also the automatic enable of LOD when u select somewhere is kinda annoying and shouldnt be automatic tbh theres people dont know how to use LOD and when LOD randomly selects somewhere when u select a world its weird..

**Comment by BramStout** [comment]
Would you be able to share a screen recording of the issues? It would make it easier for me to see what's exactly going on

**Comment by Fyoncle** [comment]
> Would you be able to share a screen recording of the issues? It would make it easier for me to see what's exactly going on

I cant record rn but, to make it simpler "When i open the lod and select somewhere, then afterwards disable the LOD checkmark and enable it again, it resets the previously selected region on the map"

**Comment by BramStout** [comment]
This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.1
