### ISSUE TITLE
Connected Textures BROKEN.

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#68]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/b96ef05d-2bc5-4700-be09-2be520a80dca)

Connected Textures i tested with Continuity in a Void World i created with few connected blocks and Stay True resource pack completely messed up.

**Comment by BramStout** [comment]
This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.1

**Comment by Fyoncle** [comment]
> This has now been fixed in the latest version of MiEx, which you can get here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.1

You're a miracle!
