### ISSUE TITLE
Challenging Cave Selection System

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#69]
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/f7120291-f55b-4363-ac38-1be14f8d588d)
To select caves we are forced to use the Y min and Y max buttons and its sometimes so annoying to get it right this way, in overworld, or either in modded worlds that have their coordinates below the bedrock, are you able to think for a alternative way to choose the caves or any underground place?

**Comment by BramStout** [comment]
Underground viewing has now been improved in the latest version of MiEx, which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.6.2
