### ISSUE TITLE
Large world files crash during import on Blender

### ISSUE THREAD

**Issue by Memetheew** [BramStoutProductions/MiEx#74]
Hello there! I've run into an issue recently:

When importing a large world USD (1000 blocks wide) Blender crashes when reaching 91%
This happens in versions of Blender 4.0 and 4.1
The same USD file loads without issue in Blender 3.6.11

**Comment by michal212345** [comment]
What's your memory usage like? Are you sure you aren't running out of ram?

**Comment by Memetheew** [comment]
RAM and VRAM don't show too much of an increase in use (I have 16 GB of ram and 6GB Vram)
GPU reaches 100% use and CPU also shows a 90% use which is to be expected. I've seen people having similar issues when importing USDs exported from older versions of Maya to blender 4.0+. That would explain why they work in older versions of Blender.

**Comment by BramStout** [comment]
Could you share your PC specs? I have the feeling that it's a bug with Blender that has to do with that CPU you have.

**Comment by BramStout** [comment]
> Sure!
> 
> CPU: AMD Ryzen 7 5800H (with Radeon Graphiccs) GPU: Nvidia RTX 3060 (Laptop GPU) 16 GB RAM
> 
> Running on Windows 10

Interesting. On my work PC I also have that Blender crashes when trying to import in large worlds. On my personal laptop, however, it seems to work fine. Now my work PC uses an AMD CPU while my personal laptop uses an Intel CPU. michal212345 has told me that he has an Intel CPU and he doesn't experience any crashes.

So, it seems to be a bug with Blender on AMD CPUs. I'd recommend to file a bug report with Blender.

**Comment by Memetheew** [comment]
Thanks for the info, I'll report it to Blender soon, I'll post over here any solutions I get or if it gets fixed
