### ISSUE TITLE
banner_<banner_id>.png doesn't exist

### ISSUE THREAD

**Issue by dav251** [BramStoutProductions/MiEx#8]
I did everything correctly but I can't find the banner.png
![image](https://github.com/BramStoutProductions/MiEx/assets/167953312/e6129e8b-4f59-484a-8931-db9a8970e640)
![image](https://github.com/BramStoutProductions/MiEx/assets/167953312/2f4fe82a-1d12-4d69-857a-69b0d0eb913c)
![image](https://github.com/BramStoutProductions/MiEx/assets/167953312/e4cd679d-c66b-48c9-b321-6320aab8df3c)

**_(I'm pretty sure I got bace_resource_pack loaded before I export)_**

I'm not sure if that's a problem because I did it wrong or something but I'm literally hitting my head against the wall to get this work lol

**Comment by BramStout** [comment]
Hi, the banner textures being created was added in v1.1.0, so you'd need to use that version or newer to get banner textures.

I have just released a new version which also fixes the other issue that you were having, so please let me know if that new version works for you! Here's the link to the latest version: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.0
