### ISSUE TITLE
Insane Corruptions On Joining World

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#81]
When you join the world on minecraft **while its opened in miex in the same time** your pc will lag as hell, give over 10 errors, then generate broken and invisible chunks, then lag for like 20 seconds insanely, then will fix itself but invisible chunks wont get fixed unless you reload the world, thats a big problem if it even happens with a accident.

**Comment by BramStout** [comment]
Minecraft worlds cannot be opened in two or more programs (like MiEx and Minecraft) at the same time. That's going to cause issues. MiEx does check when opening up a world if it's already opened up by another program, but I haven't been able to get Minecraft to check if MiEx has a world opened up.

**Comment by BramStout** [comment]
> > Minecraft worlds cannot be opened in two or more programs (like MiEx and Minecraft) at the same time. That's going to cause issues. MiEx does check when opening up a world if it's already opened up by another program, but I haven't been able to get Minecraft to check if MiEx has a world opened up.
> 
> Bram, wheres the update for weeks bro? :( i need that dimension support for MiEx, i dont wanna use mineways!!!

Still working on Bedrock Edition support. It's just a lot of work. The goal is to have a new version out somewhere this month.

Regarding modded dimension support, that will be fixed in the next version, but for now a workaround could be to copy over the dimension's file into a new world folder where the overworld files would be, so that it essentially becomes the overworld. Then MiEx can open it up without any problems.

**Comment by Fyoncle** [comment]
> > > Minecraft worlds cannot be opened in two or more programs (like MiEx and Minecraft) at the same time. That's going to cause issues. MiEx does check when opening up a world if it's already opened up by another program, but I haven't been able to get Minecraft to check if MiEx has a world opened up.
> > 
> > 
> > Bram, wheres the update for weeks bro? :( i need that dimension support for MiEx, i dont wanna use mineways!!!
> 
> Still working on Bedrock Edition support. It's just a lot of work. The goal is to have a new version out somewhere this month.
> 
> Regarding modded dimension support, that will be fixed in the next version, but for now a workaround could be to copy over the dimension's file into a new world folder where the overworld files would be, so that it essentially becomes the overworld. Then MiEx can open it up without any problems.

Oh... thanks but a hot-fix would have been great lol, take your time 🔥
