### ISSUE TITLE
Holes In Remove Caves

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#89]
VANILLA Flowers RARELY causing holes in the remove caves thingy
![image](https://github.com/BramStoutProductions/MiEx/assets/63975256/89565b0f-c0bf-4ae2-aa1e-e8d5c9458e1d)

**Comment by Fyoncle** [comment]
When using texture packs it also doesnt seem like backface culling working for leaves and stuff

**Comment by BramStout** [comment]
> VANILLA Flowers RARELY causing holes in the remove caves thingy ![image](https://private-user-images.githubusercontent.com/63975256/344428788-89565b0f-c0bf-4ae2-aa1e-e8d5c9458e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2OTE1MzAsIm5iZiI6MTcxOTY5MTIzMCwicGF0aCI6Ii82Mzk3NTI1Ni8zNDQ0Mjg3ODgtODk1NjViMGYtYzBiZi00YWUyLWFhMWUtZThkNWM5NDU4ZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIwMDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YTBmOGQzOTdiYWVkMDcwYmY0N2I3NjA0MTczMGU3OGJlYjQ1NmU1ZTYxNmJmNGFjZDhkZTdlNTA2MGEyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0dVf3fRQyLzSd7Pojqhxe7m9SPTn4MXYM-gJST6804)

This isn't "remove caves", that's a completely different thing. This looks like an issue with occlusion culling (removing faces between blocks that occlude each other). It looks like flowers can trigger a block face to get culled.

A couple of questions:
Does it always occlude the same faces, when doing multiple exports of the same region?
Does it do this with any resource pack, or only with a specific resource pack?

**Comment by BramStout** [comment]
> When using texture packs it also doesnt seem like backface culling working for leaves and stuff
> 
> VANILLA LEAVES.

I'm not entirely sure what you mean with this. Could you elaborate?

**Comment by Fyoncle** [comment]
> > When using texture packs it also doesnt seem like backface culling working for leaves and stuff
> > VANILLA LEAVES.
> 
> I'm not entirely sure what you mean with this. Could you elaborate?

Basically leaves not culling, all the faces inside them is also exported instead of only the outside of them. That is completely destructive at shadows and stuff in resource packs that doesn't use alpha for leaves but only have a solid texture. I think you stated a way to make specific blocks have special things depending on the config, but i'm not sure.

**Comment by BramStout** [comment]
> > > When using texture packs it also doesnt seem like backface culling working for leaves and stuff
> > > VANILLA LEAVES.
> > 
> > 
> > I'm not entirely sure what you mean with this. Could you elaborate?
> 
> Basically leaves not culling, all the faces inside them is also exported instead of only the outside of them. That is completely destructive at shadows and stuff in resource packs that doesn't use alpha for leaves but only have a solid texture. I think you stated a way to make specific blocks have special things depending on the config, but i'm not sure.

Minecraft renders the insides of leaves, so MiEx does this as well by default. You can change this in the `miex_config.json` file. In there you have the `leavesOcclusion` which tells MiEx to export out the blocks specified in this list the way that Minecraft renders leaves (a.k.a. keep the inside faces). You also have `transparentOcclusion` which tells MiEx to export out the blocks specified in this list the way that Minecraft renders normal transparent blocks (a.k.a. without inside faces but it doesn't occlude solid blocks so the log blocks still show up). You can also have it not in either list, in which case MiEx exports out the block as if it's a solid opaque block and it'll occlude other blocks, which also means no inner faces.

What you can do is add the following JSON data into a `miex_config.json` file in the resource pack that has solid leaves:
```JSON
{
    "leavesOcclusion.remove": ["acacia_leaves", "azalea_leaves" , "birch_leaves", "cherry_leaves", 
                                   "dark_oak_leaves", "jungle_leaves", "oak_leaves", "spruce_leaves", 
                                   "mangrove_leaves", "flowering_azalea_leaves"]
}
```
This basically removes the leaves blocks from the `leavesOcclusion` causing MiEx to see them as solid opaque blocks.

If the leaves textures do have transparency, but you just don't want the inner faces then you can do this:
```JSON
{
    "leavesOcclusion.remove": ["acacia_leaves", "azalea_leaves" , "birch_leaves", "cherry_leaves", 
                                   "dark_oak_leaves", "jungle_leaves", "oak_leaves", "spruce_leaves", 
                                   "mangrove_leaves", "flowering_azalea_leaves"],
    "transparentOcclusion.add": ["acacia_leaves", "azalea_leaves" , "birch_leaves", "cherry_leaves", 
                                   "dark_oak_leaves", "jungle_leaves", "oak_leaves", "spruce_leaves", 
                                   "mangrove_leaves", "flowering_azalea_leaves"]
}
```
Which removes the leaves from `leavesOcclusion` and adds them to `transparentOcclusion` causing MiEx to see them as normal transparent blocks, where it'll remove inner faces but these transparent blocks don't occlude solid opaque blocks.
