### ISSUE TITLE
World exporting process stuck in 1.1.0

### ISSUE THREAD

**Issue by dav251** [BramStoutProductions/MiEx#9]
![image](https://github.com/BramStoutProductions/MiEx/assets/167953312/278a4342-6bae-4639-a286-6077e7191b06)

For some reason it loads normally and then stops at this point for a long time and never moves **(this only happens in v1.1.0)**

I tried 1.0.0 and it works just fine
but for some reason the banner.png doesn't exist.

**Comment by michal212345** [comment]
Updating to Java 22 fixed that for me

**Comment by BramStout** [comment]
MiEx is supposed to be compatible with Java 8, but a single line of code that required Java 11 or newer slipped through. I have fixed it so now MiEx should run on Java 8 and up.

Here's the link to the latest version: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.2.0

Please let me know if this works for you!
