### ISSUE TITLE
Blender 4.2 Changes

### ISSUE THREAD

**Issue by Fyoncle** [BramStoutProductions/MiEx#97]
![image](https://github.com/user-attachments/assets/4612a4cf-800b-42dd-b590-1201f28a2919)
Yep, if im not reading it wrong or understanding it wrong, Blender 4.2 now supports MaterialX and i wanna know if this USD format related changes may help MiEx's improvement in the Blender side.

**Comment by Fyoncle** [comment]
> Unfortunately, USD imports regarding materials is still very lacking. Blender 4.2 supports exporting Blender materials to MaterialX but the documentation doesn't say it supports importing MaterialX materials.
> 
> Using the Blender addon to import in worlds is still the best way, since that also allows you to specify Blender materials directly, rather than specifying MaterialX materials that then have to be converted into Blender materials. Being able to specify Blender materials directly, is way more powerful

That is sad, also do you have a planned release date for the MiEx's new version? i saw you active on the Projects on GitHub

**Comment by BramStout** [comment]
> > Unfortunately, USD imports regarding materials is still very lacking. Blender 4.2 supports exporting Blender materials to MaterialX but the documentation doesn't say it supports importing MaterialX materials.
> > Using the Blender addon to import in worlds is still the best way, since that also allows you to specify Blender materials directly, rather than specifying MaterialX materials that then have to be converted into Blender materials. Being able to specify Blender materials directly, is way more powerful
> 
> That is sad, also do you have a planned release date for the MiEx's new version? i saw you active on the Projects on GitHub

Luckily, with the new Blender addon things should just work. For the next version of MiEx there are a few small improvements to it.

At this moment there is unfortunately no planned release date for the next version. It is feature complete, but I do want to extensively test it to make sure there are as few bugs as possible. The projects page on the GitHub repo is indeed kept up to date with the development of the next version. I also have client work which does slow down development. This next version is a big version with lots of new stuff and lots of stuff changed, and I want to make sure that it's as good as it can be.

**Comment by Fyoncle** [comment]
> > > Unfortunately, USD imports regarding materials is still very lacking. Blender 4.2 supports exporting Blender materials to MaterialX but the documentation doesn't say it supports importing MaterialX materials.
> > > Using the Blender addon to import in worlds is still the best way, since that also allows you to specify Blender materials directly, rather than specifying MaterialX materials that then have to be converted into Blender materials. Being able to specify Blender materials directly, is way more powerful
> > 
> > 
> > That is sad, also do you have a planned release date for the MiEx's new version? i saw you active on the Projects on GitHub
> 
> Luckily, with the new Blender addon things should just work. For the next version of MiEx there are a few small improvements to it.
> 
> At this moment there is unfortunately no planned release date for the next version. It is feature complete, but I do want to extensively test it to make sure there are as few bugs as possible. The projects page on the GitHub repo is indeed kept up to date with the development of the next version. I also have client work which does slow down development. This next version is a big version with lots of new stuff and lots of stuff changed, and I want to make sure that it's as good as it can be.

Take your time, be the king of the world exporters! 👑
